# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
before_all do |_lane, options|
  ENV["FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT"]="1"
  ENV["FASTLANE_ITUNES_TRANSPORTER_PATH"]="/Applications/Transporter.app/Contents/itms"  
  update_fastlane
end
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    changelog_from_git_commits
    increment_build_number(xcodeproj: "./ios/HocSo.xcodeproj")
    build_app(workspace: "./ios/HocSo.xcworkspace", scheme: "HocSo")
    pilot
    commit_version_bump(xcodeproj: "./ios/HocSo.xcodeproj")
    add_git_tag
    push_to_git_remote
  end
end

platform :android do
  lane :apk do
    gradle(task: "clean assembleRelease", project_dir: "./android")
    open "android/app/build/outputs/apk/release"
  end

  lane :playstore do
    ensure_git_status_clean
    previous_build_number = google_play_track_version_codes()[0]

    current_build_number = previous_build_number + 1

    increment_version_code(
      version_code: current_build_number
    )
    gradle(task: "clean bundleRelease", project_dir: "./android")
    upload_to_play_store
    push_to_git_remote
  end
end
