# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    changelog_from_git_commits
    increment_build_number(xcodeproj: "./ios/HocSo.xcodeproj")
    build_app(workspace: "./ios/HocSo.xcworkspace", scheme: "HocSo")
    upload_to_testflight(ipa: './HocSo.ipa')
    commit_version_bump(xcodeproj: "./ios/HocSo.xcodeproj")
    add_git_tag
    push_to_git_remote
  end
end
