export interface Word {
  en: string
  dashEn: string
  vi: string
  category: string
}

export const words: Word[] = [
  { category: "animal", en: "cat", vi: "con mèo", dashEn: "cat" },
  { category: "animal", en: "dog", vi: "chó", dashEn: "dog" },
  { category: "animal", en: "cow", vi: "con bò", dashEn: "cow" },
  { category: "animal", en: "bat", vi: "con dơi", dashEn: "bat" },
  { category: "animal", en: "bird", vi: "chim", dashEn: "bird" },
  { category: "animal", en: "crab", vi: "con cua", dashEn: "crab" },
  { category: "animal", en: "deer", vi: "con nai", dashEn: "deer" },
  { category: "animal", en: "dolphin", vi: "cá heo", dashEn: "dolphin" },
  { category: "animal", en: "donkey", vi: "con lừa", dashEn: "donkey" },
  { category: "animal", en: "duck", vi: "con vịt", dashEn: "duck" },
  { category: "animal", en: "elephant", vi: "con voi", dashEn: "elephant" },
  { category: "animal", en: "frog", vi: "con ếch", dashEn: "frog" },
  { category: "animal", en: "giraffe", vi: "hươu cao cổ", dashEn: "giraffe" },
  { category: "animal", en: "goat", vi: "con dê", dashEn: "goat" },
  { category: "animal", en: "hippo", vi: "con hà mã", dashEn: "hippo" },
  { category: "animal", en: "horse", vi: "ngựa", dashEn: "horse" },
  { category: "animal", en: "leopard", vi: "con báo", dashEn: "leopard" },
  { category: "animal", en: "lion", vi: "con sư tử", dashEn: "lion" },
  { category: "animal", en: "monkey", vi: "con khỉ", dashEn: "monkey" },
  { category: "animal", en: "fish", vi: "cá", dashEn: "fish" },
  { category: "animal", en: "rabbit", vi: "con thỏ", dashEn: "rabbit" },
  { category: "animal", en: "squid", vi: "con mực", dashEn: "squid" },
  { category: "animal", en: "pig", vi: "con lợn", dashEn: "pig" },
  { category: "animal", en: "tiger", vi: "con hổ", dashEn: "tiger" },
  { category: "animal", en: "turtle", vi: "con rùa", dashEn: "turtle" },
  { category: "animal", en: "sheep", vi: "con cừu", dashEn: "sheep" },
  { category: "animal", en: "shrimp", vi: "con tôm", dashEn: "shrimp" },
  { category: "animal", en: "chicken", vi: "con gà", dashEn: "chicken" },
  { category: "animal", en: "hen", vi: "con gà mái", dashEn: "hen" },
  { category: "animal", en: "rooster", vi: "gà trống", dashEn: "rooster" },
  { category: "number", en: "one", vi: "một", dashEn: "one" },
  { category: "number", en: "two", vi: "hai", dashEn: "two" },
  { category: "number", en: "three", vi: "ba", dashEn: "three" },
  { category: "number", en: "four", vi: "bốn", dashEn: "four" },
  { category: "number", en: "five", vi: "năm", dashEn: "five" },
  { category: "number", en: "six", vi: "sáu", dashEn: "six" },
  { category: "number", en: "seven", vi: "bảy", dashEn: "seven" },
  { category: "number", en: "nine", vi: "chín", dashEn: "nine" },
  { category: "animal", en: "Lemur", vi: "vượn cáo", dashEn: "Lemur" },
  { category: "animal", en: "Lizard", vi: "Thằn lằn", dashEn: "Lizard" },
  { category: "animal", en: "Lobster", vi: "tôm hùm", dashEn: "Lobster" },
  { category: "animal", en: "alligator", vi: "cá sấu Mỹ", dashEn: "alligator" },
  { category: "animal", en: "anteater", vi: "Thú ăn kiến", dashEn: "anteater" },
  { category: "animal", en: "artic fox", vi: "cáo tuyết", dashEn: "artic-fox" },
  { category: "animal", en: "badger", vi: "con lửng", dashEn: "badger" },
  { category: "animal", en: "bear", vi: "con gấu", dashEn: "bear" },
  { category: "animal", en: "beaver", vi: "hải ly", dashEn: "beaver" },
  { category: "animal", en: "boar", vi: "con lợn rừng", dashEn: "boar" },
  { category: "animal", en: "bugs", vi: "côn trùng", dashEn: "bugs" },
  { category: "animal", en: "camel", vi: "con lạc đà", dashEn: "camel" },
  { category: "animal", en: "crocodile", vi: "Cá sấu", dashEn: "crocodile" },
  { category: "animal", en: "eagle", vi: "Đại bàng", dashEn: "eagle" },
  { category: "animal", en: "eel", vi: "con lươn", dashEn: "eel" },
  { category: "animal", en: "flamingo", vi: "Chim hồng hạc", dashEn: "flamingo" },
  { category: "animal", en: "fox", vi: "cáo", dashEn: "fox" },
  { category: "animal", en: "gorilla", vi: "con khỉ đột", dashEn: "gorilla" },
  { category: "animal", en: "guinea pig", vi: "chuột bạch", dashEn: "guinea-pig" },
  { category: "animal", en: "hawk", vi: "chim ưng", dashEn: "hawk" },
  { category: "animal", en: "hedgehog", vi: "nhím", dashEn: "hedgehog" },
  { category: "animal", en: "hyena", vi: "Linh cẩu", dashEn: "hyena" },
  { category: "animal", en: "iguana", vi: "Kỳ nhông", dashEn: "iguana" },
  { category: "animal", en: "jellyfish", vi: "con sứa", dashEn: "jellyfish" },
  { category: "animal", en: "kangaroo", vi: "con chuột túi", dashEn: "kangaroo" },
  { category: "animal", en: "killer whale", vi: "cá voi sát thủ", dashEn: "killer-whale" },
  { category: "animal", en: "koala", vi: "gấu túi", dashEn: "koala" },
  { category: "animal", en: "llama", vi: "lạc đà không bướu", dashEn: "llama" },
  { category: "animal", en: "mole", vi: "chuột chũi", dashEn: "mole" },
  { category: "animal", en: "moose", vi: "nai sừng tấm", dashEn: "moose" },
  { category: "animal", en: "mouse", vi: "con chuột nhỏ", dashEn: "mouse" },
  { category: "animal", en: "narwhal", vi: "kỳ lân biển", dashEn: "narwhal" },
  { category: "animal", en: "newt", vi: "sa giông", dashEn: "newt" },
  { category: "animal", en: "octopus", vi: "bạch tuộc", dashEn: "octopus" },
  { category: "animal", en: "ostritch", vi: "đà điểu", dashEn: "ostritch" },
  { category: "animal", en: "otter", vi: "rái cá", dashEn: "otter" },
  { category: "animal", en: "owl", vi: "con cú", dashEn: "owl" },
  { category: "animal", en: "panda", vi: "gấu trúc", dashEn: "panda" },
  { category: "animal", en: "parrot", vi: "con vẹt", dashEn: "parrot" },
  { category: "animal", en: "peacock", vi: "con công", dashEn: "peacock" },
  { category: "animal", en: "penguin", vi: "chim cánh cụt", dashEn: "penguin" },
  { category: "animal", en: "pigeon", vi: "chim bồ câu", dashEn: "pigeon" },
  { category: "animal", en: "plankton", vi: "sinh vật phù du", dashEn: "plankton" },
  { category: "animal", en: "platypus", vi: "thú mỏ vịt", dashEn: "platypus" },
  { category: "animal", en: "polar bear", vi: "gấu Bắc cực", dashEn: "polar-bear" },
  { category: "animal", en: "puffin", vi: "chim hải âu", dashEn: "puffin" },
  { category: "animal", en: "quail", vi: "chim cút", dashEn: "quail" },
  { category: "animal", en: "queen bee", vi: "ong chúa", dashEn: "queen-bee" },
  { category: "animal", en: "racoon", vi: "gấu mèo", dashEn: "racoon" },
  { category: "animal", en: "rat", vi: "con chuột", dashEn: "rat" },
  { category: "animal", en: "rhino", vi: "tê giác", dashEn: "rhino" },
  { category: "animal", en: "scorpion", vi: "bọ cạp", dashEn: "scorpion" },
  { category: "animal", en: "seahorse", vi: "cá ngựa", dashEn: "seahorse" },
  { category: "animal", en: "seal", vi: "hải cẩu", dashEn: "seal" },
  { category: "animal", en: "shark", vi: "cá mập", dashEn: "shark" },
  { category: "animal", en: "skunk", vi: "chồn hôi", dashEn: "skunk" },
  { category: "animal", en: "sloth", vi: "con lười", dashEn: "sloth" },
  { category: "animal", en: "snake", vi: "con rắn", dashEn: "snake" },
  { category: "animal", en: "squirrel", vi: "con sóc", dashEn: "squirrel" },
  { category: "animal", en: "starfish", vi: "sao biển", dashEn: "starfish" },
  { category: "animal", en: "stingray", vi: "cá đuối", dashEn: "stingray" },
  { category: "animal", en: "swordfish", vi: "cá kiếm", dashEn: "swordfish" },
  { category: "animal", en: "tarantula", vi: "loài nhện", dashEn: "tarantula" },
  { category: "animal", en: "urchin", vi: "con nhím", dashEn: "urchin" },
  { category: "animal", en: "vulture", vi: "con kền kền", dashEn: "vulture" },
  { category: "animal", en: "walrus", vi: "hải mã", dashEn: "walrus" },
  { category: "animal", en: "whale", vi: "cá voi", dashEn: "whale" },
  { category: "animal", en: "wolf", vi: "chó sói", dashEn: "wolf" },
  { category: "animal", en: "yak", vi: "bò Tây Tạng", dashEn: "yak" },
  { category: "animal", en: "zebra", vi: "ngựa vằn", dashEn: "zebra" },
  { category: "activity", en: "dance", vi: "Khiêu vũ", dashEn: "dance" },
  { category: "activity", en: "drink", vi: "Uống", dashEn: "drink" },
  { category: "activity", en: "eat", vi: "Ăn", dashEn: "eat" },
  { category: "activity", en: "hike", vi: "Đi bộ", dashEn: "hike" },
  { category: "activity", en: "jog", vi: "Chạy bộ", dashEn: "jog" },
  { category: "activity", en: "play", vi: "Chơi", dashEn: "play" },
  { category: "activity", en: "read", vi: "Đọc", dashEn: "read" },
  { category: "activity", en: "ride", vi: "Cưỡi", dashEn: "ride" },
  { category: "activity", en: "run", vi: "Chạy", dashEn: "run" },
  { category: "activity", en: "sing", vi: "Hát", dashEn: "sing" },
  { category: "activity", en: "sleep", vi: "Ngủ", dashEn: "sleep" },
  { category: "activity", en: "watch TV", vi: "xem TV", dashEn: "watch-TV" },
  { category: "adjective", en: "bad", vi: "Xấu", dashEn: "bad" },
  { category: "adjective", en: "beautiful", vi: "Xinh", dashEn: "beautiful" },
  { category: "adjective", en: "big", vi: "To lớn", dashEn: "big" },
  { category: "adjective", en: "bitter", vi: "Vị đắng", dashEn: "bitter" },
  { category: "adjective", en: "bright", vi: "Sáng", dashEn: "bright" },
  { category: "adjective", en: "cheap", vi: "Rẻ", dashEn: "cheap" },
  { category: "adjective", en: "clean", vi: "Sạch  sẽ", dashEn: "clean" },
  { category: "adjective", en: "cold", vi: "Lạnh", dashEn: "cold" },
  { category: "adjective", en: "dark", vi: "Tối", dashEn: "dark" },
  { category: "adjective", en: "day", vi: "Ngày", dashEn: "day" },
  { category: "adjective", en: "deep", vi: "Sâu", dashEn: "deep" },
  { category: "adjective", en: "dirty", vi: "Bẩn", dashEn: "dirty" },
  { category: "adjective", en: "dry", vi: "Khô", dashEn: "dry" },
  { category: "adjective", en: "empty", vi: "Trống", dashEn: "empty" },
  { category: "adjective", en: "expensive", vi: "Đắt", dashEn: "expensive" },
  { category: "adjective", en: "fast", vi: "Nhanh", dashEn: "fast" },
  { category: "adjective", en: "fat", vi: "Béo", dashEn: "fat" },
  { category: "adjective", en: "few", vi: "Một vài", dashEn: "few" },
  { category: "adjective", en: "full", vi: "Đầy", dashEn: "full" },
  { category: "adjective", en: "good", vi: "Tốt", dashEn: "good" },
  { category: "adjective", en: "hard", vi: "Cứng", dashEn: "hard" },
  { category: "adjective", en: "heavy", vi: "Nặng", dashEn: "heavy" },
  { category: "adjective", en: "hot", vi: "Nóng", dashEn: "hot" },
  { category: "adjective", en: "light", vi: "Nhẹ", dashEn: "light" },
  { category: "adjective", en: "long", vi: "Dài", dashEn: "long" },
  { category: "adjective", en: "many", vi: "Nhiều", dashEn: "many" },
  { category: "adjective", en: "new", vi: "Mới", dashEn: "new" },
  { category: "adjective", en: "night", vi: "Đêm", dashEn: "night" },
  { category: "adjective", en: "noisy", vi: "Ồn ào", dashEn: "noisy" },
  { category: "adjective", en: "old", vi: "Cũ", dashEn: "old" },
  { category: "adjective", en: "quiet", vi: "Im lặng", dashEn: "quiet" },
  { category: "adjective", en: "rough", vi: "Thô", dashEn: "rough" },
  { category: "adjective", en: "shallow", vi: "Nông", dashEn: "shallow" },
  { category: "adjective", en: "short", vi: "Ngắn", dashEn: "short" },
  { category: "adjective", en: "slow", vi: "Chậm", dashEn: "slow" },
  { category: "adjective", en: "small", vi: "Bé nhỏ", dashEn: "small" },
  { category: "adjective", en: "smooth", vi: "Trơn tru", dashEn: "smooth" },
  { category: "adjective", en: "soft", vi: "Mềm mại", dashEn: "soft" },
  { category: "adjective", en: "strong", vi: "Mạnh mẽ", dashEn: "strong" },
  { category: "adjective", en: "sweet", vi: "Ngọt", dashEn: "sweet" },
  { category: "adjective", en: "tall", vi: "Cao", dashEn: "tall" },
  { category: "adjective", en: "thin", vi: "Gầy", dashEn: "thin" },
  { category: "adjective", en: "ugly", vi: "Xấu xí", dashEn: "ugly" },
  { category: "adjective", en: "weak", vi: "Yếu đuối", dashEn: "weak" },
  { category: "adjective", en: "wet", vi: "Ướt", dashEn: "wet" },
  { category: "adjective", en: "young", vi: "Trẻ", dashEn: "young" },
  { category: "alphabet", en: "A", vi: "A", dashEn: "A" },
  { category: "alphabet", en: "B", vi: "B", dashEn: "B" },
  { category: "alphabet", en: "C", vi: "C", dashEn: "C" },
  { category: "alphabet", en: "D", vi: "D", dashEn: "D" },
  { category: "alphabet", en: "E", vi: "E", dashEn: "E" },
  { category: "alphabet", en: "F", vi: "F", dashEn: "F" },
  { category: "alphabet", en: "G", vi: "G", dashEn: "G" },
  { category: "alphabet", en: "H", vi: "H", dashEn: "H" },
  { category: "alphabet", en: "I", vi: "I", dashEn: "I" },
  { category: "alphabet", en: "J", vi: "J", dashEn: "J" },
  { category: "alphabet", en: "K", vi: "K", dashEn: "K" },
  { category: "alphabet", en: "L", vi: "L", dashEn: "L" },
  { category: "alphabet", en: "M", vi: "M", dashEn: "M" },
  { category: "alphabet", en: "N", vi: "N", dashEn: "N" },
  { category: "alphabet", en: "O", vi: "O", dashEn: "O" },
  { category: "alphabet", en: "P", vi: "P", dashEn: "P" },
  { category: "alphabet", en: "Q", vi: "Q", dashEn: "Q" },
  { category: "alphabet", en: "R", vi: "R", dashEn: "R" },
  { category: "alphabet", en: "S", vi: "S", dashEn: "S" },
  { category: "alphabet", en: "T", vi: "T", dashEn: "T" },
  { category: "alphabet", en: "U", vi: "U", dashEn: "U" },
  { category: "alphabet", en: "V", vi: "V", dashEn: "V" },
  { category: "alphabet", en: "W", vi: "W", dashEn: "W" },
  { category: "alphabet", en: "X", vi: "X", dashEn: "X" },
  { category: "alphabet", en: "Y", vi: "Y", dashEn: "Y" },
  { category: "alphabet", en: "Z", vi: "Z", dashEn: "Z" },
  {
    category: "amusement-park",
    en: "amusement park",
    vi: "Công viên giải trí",
    dashEn: "amusement-park",
  },
  { category: "amusement-park", en: "boat swing", vi: "Đu thuyền", dashEn: "boat-swing" },
  {
    category: "amusement-park",
    en: "bouncy castle",
    vi: "Lâu đài bơm hơi",
    dashEn: "bouncy-castle",
  },
  { category: "amusement-park", en: "bumper cars", vi: "Xe điện đụng", dashEn: "bumper-cars" },
  { category: "amusement-park", en: "chair swing", vi: "Ghế đu mây", dashEn: "chair-swing" },
  {
    category: "amusement-park",
    en: "cup and saucer",
    vi: "Đu quay cốc và đĩa",
    dashEn: "cup-and-saucer",
  },
  {
    category: "amusement-park",
    en: "ferris wheel",
    vi: "Đu quay khổng lồ",
    dashEn: "ferris-wheel",
  },
  { category: "amusement-park", en: "go karts", vi: "Đua xe go karts", dashEn: "go-karts" },
  { category: "amusement-park", en: "haunted house", vi: "Nhà ma", dashEn: "haunted-house" },
  {
    category: "amusement-park",
    en: "merry go round",
    vi: "Đu quay ngựa",
    dashEn: "merry-go-round",
  },
  {
    category: "amusement-park",
    en: "roller coaster",
    vi: "Tàu lượn siêu tốc",
    dashEn: "roller-coaster",
  },
  { category: "amusement-park", en: "ticket booth", vi: "Buồng vé", dashEn: "ticket-booth" },
  { category: "bathroom", en: "Q-tip", vi: "tăm bông", dashEn: "Q-tip" },
  { category: "bathroom", en: "bath mat", vi: "thảm tắm", dashEn: "bath-mat" },
  { category: "bathroom", en: "bathtub", vi: "bồn tắm", dashEn: "bathtub" },
  { category: "bathroom", en: "comb", vi: "cái lược", dashEn: "comb" },
  { category: "bathroom", en: "dental floss", vi: "chỉ nha khoa", dashEn: "dental-floss" },
  { category: "bathroom", en: "hair dryer", vi: "máy sấy tóc", dashEn: "hair-dryer" },
  { category: "bathroom", en: "hand towel", vi: "khăn tay", dashEn: "hand-towel" },
  { category: "bathroom", en: "lotion", vi: "kem dưỡng da", dashEn: "lotion" },
  { category: "bathroom", en: "makeup", vi: "trang điểm", dashEn: "makeup" },
  { category: "bathroom", en: "mouthwash", vi: "nước súc miệng", dashEn: "mouthwash" },
  { category: "bathroom", en: "razor", vi: "dao cạo", dashEn: "razor" },
  { category: "bathroom", en: "shampoo", vi: "dầu gội đầu", dashEn: "shampoo" },
  { category: "bathroom", en: "shaving cream", vi: "kem cạo râu", dashEn: "shaving-cream" },
  { category: "bathroom", en: "shower", vi: "vòi hoa sen", dashEn: "shower" },
  { category: "bathroom", en: "soap", vi: "xà bông", dashEn: "soap" },
  { category: "bathroom", en: "sponge", vi: "bọt biển", dashEn: "sponge" },
  { category: "bathroom", en: "toilet paper", vi: "giấy vệ sinh", dashEn: "toilet-paper" },
  { category: "bathroom", en: "toilet", vi: "phòng vệ sinh", dashEn: "toilet" },
  { category: "bathroom", en: "toothbrush", vi: "Bàn chải đánh răng", dashEn: "toothbrush" },
  { category: "bathroom", en: "toothpaste", vi: "kem đánh răng", dashEn: "toothpaste" },
  { category: "bathroom", en: "towel", vi: "khăn tắm", dashEn: "towel" },
  { category: "number", en: "eight", vi: "tám", dashEn: "eight" },
  { category: "number", en: "eighteen", vi: "mười tám", dashEn: "eighteen" },
  { category: "number", en: "eighty", vi: "tám mươi", dashEn: "eighty" },
  { category: "number", en: "eleven", vi: "mười một", dashEn: "eleven" },
  { category: "number", en: "fifteen", vi: "mười lăm", dashEn: "fifteen" },
  { category: "number", en: "fifty", vi: "năm mươi", dashEn: "fifty" },
  { category: "number", en: "forty", vi: "bốn mươi", dashEn: "forty" },
  { category: "number", en: "fourteen", vi: "mười bốn", dashEn: "fourteen" },
  { category: "number", en: "nineteen", vi: "mười chín", dashEn: "nineteen" },
  { category: "number", en: "ninety", vi: "chín mươi", dashEn: "ninety" },
  { category: "number", en: "one hundred", vi: "một trăm", dashEn: "one-hundred" },
  { category: "number", en: "seventeen", vi: "mười bảy", dashEn: "seventeen" },
  { category: "number", en: "seventy", vi: "bảy mươi", dashEn: "seventy" },
  { category: "number", en: "sixteen", vi: "mười sáu", dashEn: "sixteen" },
  { category: "number", en: "sixty", vi: "sáu mươi", dashEn: "sixty" },
  { category: "number", en: "ten", vi: "mười", dashEn: "ten" },
  { category: "number", en: "thirteen", vi: "mười ba", dashEn: "thirteen" },
  { category: "number", en: "thirty", vi: "ba mươi", dashEn: "thirty" },
  { category: "number", en: "twelve", vi: "mười hai", dashEn: "twelve" },
  { category: "number", en: "twenty", vi: "hai mươi", dashEn: "twenty" },
  { category: "beach", en: "beach bag", vi: "Túi đi biển", dashEn: "beach-bag" },
  { category: "beach", en: "beach ball", vi: "Bóng chuyền bãi biển", dashEn: "beach-ball" },
  { category: "beach", en: "bucket", vi: "Cái xô", dashEn: "bucket" },
  { category: "beach", en: "camera", vi: "Máy ảnh", dashEn: "camera" },
  { category: "beach", en: "deckchair", vi: "Ghế xếp", dashEn: "deckchair" },
  { category: "beach", en: "goggles", vi: "Kính bơi", dashEn: "goggles" },
  { category: "beach", en: "ice box", vi: "Thùng đựng đá", dashEn: "ice-box" },
  { category: "beach", en: "ice cream", vi: "Kem", dashEn: "ice-cream" },
  { category: "beach", en: "parasol", vi: "Ô che nắng", dashEn: "parasol" },
  { category: "beach", en: "sand castle", vi: "Lâu đài cát", dashEn: "sand-castle" },
  { category: "beach", en: "sand", vi: "Cát", dashEn: "sand" },
  { category: "beach", en: "seagull", vi: "Hải âu", dashEn: "seagull" },
  { category: "beach", en: "shells", vi: "Vỏ sò", dashEn: "shells" },
  { category: "beach", en: "snorkel", vi: "Ống thở", dashEn: "snorkel" },
  { category: "beach", en: "spade", vi: "Cái xẻng", dashEn: "spade" },
  { category: "beach", en: "sun hat", vi: "Mũ chống nắng", dashEn: "sun-hat" },
  { category: "beach", en: "sun shelter", vi: "Dù chống nắng", dashEn: "sun-shelter" },
  { category: "beach", en: "sunglasses", vi: "Kính râm", dashEn: "sunglasses" },
  { category: "beach", en: "sunscreen", vi: "Kem chống nắng", dashEn: "sunscreen" },
  { category: "beach", en: "surfboard", vi: "Ván lướt sóng", dashEn: "surfboard" },
  { category: "beach", en: "swim trunks", vi: "Quần bơi", dashEn: "swim-trunks" },
  { category: "beach", en: "swimsuit", vi: "Đồ bơi", dashEn: "swimsuit" },
  { category: "body-part", en: "arm", vi: "Cánh tay", dashEn: "arm" },
  { category: "body-part", en: "body", vi: "Cơ thể", dashEn: "body" },
  { category: "body-part", en: "ear", vi: "Tai", dashEn: "ear" },
  { category: "body-part", en: "elbow", vi: "Khuỷu tay", dashEn: "elbow" },
  { category: "body-part", en: "eye", vi: "Mắt", dashEn: "eye" },
  { category: "body-part", en: "eyebrow", vi: "Lông mày", dashEn: "eyebrow" },
  { category: "body-part", en: "eyelash", vi: "Lông mi", dashEn: "eyelash" },
  { category: "body-part", en: "face", vi: "Khuôn mặt", dashEn: "face" },
  { category: "body-part", en: "feet", vi: "Bàn chân", dashEn: "feet" },
  { category: "body-part", en: "finger", vi: "Ngón tay", dashEn: "finger" },
  { category: "body-part", en: "foot", vi: "Chân", dashEn: "foot" },
  { category: "body-part", en: "hair", vi: "Tóc", dashEn: "hair" },
  { category: "body-part", en: "hand", vi: "Bàn tay", dashEn: "hand" },
  { category: "body-part", en: "head", vi: "Đầu", dashEn: "head" },
  { category: "body-part", en: "knee", vi: "Đầu gối", dashEn: "knee" },
  { category: "body-part", en: "lips", vi: "Môi", dashEn: "lips" },
  { category: "body-part", en: "mouth", vi: "Miệng", dashEn: "mouth" },
  { category: "body-part", en: "neck", vi: "Cổ", dashEn: "neck" },
  { category: "body-part", en: "nose", vi: "Mũi", dashEn: "nose" },
  { category: "body-part", en: "shoulder", vi: "Vai", dashEn: "shoulder" },
  { category: "body-part", en: "teeth", vi: "Răng", dashEn: "teeth" },
  { category: "body-part", en: "thumb", vi: "Ngón cái", dashEn: "thumb" },
  { category: "body-part", en: "toes", vi: "Ngón chân", dashEn: "toes" },
  { category: "body-part", en: "tongue", vi: "Lưỡi", dashEn: "tongue" },
  { category: "bug", en: "ant", vi: "Kiến", dashEn: "ant" },
  { category: "bug", en: "bee", vi: "Ong", dashEn: "bee" },
  { category: "bug", en: "beetle", vi: "Bọ cánh cứng", dashEn: "beetle" },
  { category: "bug", en: "butterfly", vi: "Bướm", dashEn: "butterfly" },
  { category: "bug", en: "caterpillar", vi: "Sâu bướm", dashEn: "caterpillar" },
  { category: "bug", en: "dragonfly", vi: "Chuồn chuồn", dashEn: "dragonfly" },
  { category: "bug", en: "fly", vi: "Ruồi", dashEn: "fly" },
  { category: "bug", en: "grasshopper", vi: "Châu chấu", dashEn: "grasshopper" },
  { category: "bug", en: "ladybug", vi: "Bọ rùa", dashEn: "ladybug" },
  { category: "bug", en: "snail", vi: "Ốc sên", dashEn: "snail" },
  { category: "bug", en: "spider", vi: "Nhện", dashEn: "spider" },
  { category: "bug", en: "worm", vi: "con sâu", dashEn: "worm" },
  { category: "christmas", en: "Christmas hat", vi: "Mũ giáng sinh", dashEn: "Christmas-hat" },
  {
    category: "christmas",
    en: "Christmas lights",
    vi: "Đèn giáng sinh",
    dashEn: "Christmas-lights",
  },
  {
    category: "christmas",
    en: "Christmas tree",
    vi: "Cây thông giáng sinh",
    dashEn: "Christmas-tree",
  },
  { category: "christmas", en: "Christmas", vi: "Giáng sinh", dashEn: "Christmas" },
  { category: "christmas", en: "Santa", vi: "Ông già noel", dashEn: "Santa" },
  { category: "christmas", en: "bells", vi: "Chuông", dashEn: "bells" },
  { category: "christmas", en: "candy cane", vi: "Cây kẹo", dashEn: "candy-cane" },
  { category: "christmas", en: "chimney", vi: "Ống khói", dashEn: "chimney" },
  { category: "christmas", en: "decorations", vi: "Đồ trang trí", dashEn: "decorations" },
  { category: "christmas", en: "elf", vi: "Yêu tinh", dashEn: "elf" },
  { category: "christmas", en: "sleigh", vi: "Xe trượt tuyết", dashEn: "sleigh" },
  { category: "christmas", en: "snowflake", vi: "Bông tuyết", dashEn: "snowflake" },
  { category: "christmas", en: "snowglobe", vi: "Quả cầu tuyết", dashEn: "snowglobe" },
  { category: "christmas", en: "snowman", vi: "Người tuyết", dashEn: "snowman" },
  { category: "christmas", en: "toys", vi: "Đồ chơi", dashEn: "toys" },
  { category: "christmas", en: "turkey", vi: "Gà tây", dashEn: "turkey" },
  { category: "christmas", en: "wreath", vi: "Vòng hoa", dashEn: "wreath" },
  { category: "classroom", en: "book", vi: "Quyển sách", dashEn: "book" },
  { category: "classroom", en: "calculator", vi: "Máy tính cầm tay", dashEn: "calculator" },
  { category: "classroom", en: "calendar", vi: "Lịch", dashEn: "calendar" },
  { category: "classroom", en: "chalkboard", vi: "Bảng phấn", dashEn: "chalkboard" },
  { category: "classroom", en: "clock", vi: "Đồng đồ", dashEn: "clock" },
  { category: "classroom", en: "computer", vi: "Máy vi tính", dashEn: "computer" },
  { category: "classroom", en: "crayons", vi: "Bút màu", dashEn: "crayons" },
  { category: "classroom", en: "desk", vi: "Bàn học", dashEn: "desk" },
  { category: "classroom", en: "eraser", vi: "Cục tẩy", dashEn: "eraser" },
  { category: "classroom", en: "globe", vi: "Khối cầu", dashEn: "globe" },
  { category: "classroom", en: "glue", vi: "Keo dính", dashEn: "glue" },
  { category: "classroom", en: "marker", vi: "Bút dầu", dashEn: "marker" },
  { category: "classroom", en: "microscope", vi: "Kính hiển vi", dashEn: "microscope" },
  { category: "classroom", en: "notebook", vi: "Quyển vở", dashEn: "notebook" },
  { category: "classroom", en: "paper clip", vi: "Kẹp giấy", dashEn: "paper-clip" },
  { category: "classroom", en: "pen", vi: "Bút", dashEn: "pen" },
  { category: "classroom", en: "pencil sharpener", vi: "Gọt bút chì", dashEn: "pencil-sharpener" },
  { category: "classroom", en: "pencil", vi: "Bút chì", dashEn: "pencil" },
  { category: "classroom", en: "ruler", vi: "Thước kẻ", dashEn: "ruler" },
  { category: "classroom", en: "scissors", vi: "Cái kéo", dashEn: "scissors" },
  { category: "classroom", en: "water bottle", vi: "Bình nước", dashEn: "water-bottle" },
  { category: "classroom", en: "whiteboard", vi: "Bảng trắng", dashEn: "whiteboard" },
  { category: "clothing", en: "apron", vi: "Tạp dề", dashEn: "apron" },
  { category: "clothing", en: "backpack", vi: "Balo", dashEn: "backpack" },
  { category: "clothing", en: "bag", vi: "Túi", dashEn: "bag" },
  { category: "clothing", en: "bathrobe", vi: "Áo choàng tắm", dashEn: "bathrobe" },
  { category: "clothing", en: "belt", vi: "Thắt lưng", dashEn: "belt" },
  { category: "clothing", en: "boots", vi: "Giày bốt", dashEn: "boots" },
  { category: "clothing", en: "bow tie", vi: "Cái nơ", dashEn: "bow-tie" },
  { category: "clothing", en: "briefcase", vi: "Vali", dashEn: "briefcase" },
  { category: "clothing", en: "bubble coat", vi: "Áo bong bóng", dashEn: "bubble-coat" },
  { category: "clothing", en: "cap", vi: "Mũ lưỡi chai", dashEn: "cap" },
  { category: "clothing", en: "coat", vi: "Áo choàng", dashEn: "coat" },
  { category: "clothing", en: "cowboy boots", vi: "Bốt cao bồi", dashEn: "cowboy-boots" },
  { category: "clothing", en: "diaper", vi: "Tã lót", dashEn: "diaper" },
  { category: "clothing", en: "dress", vi: "Cái đầm", dashEn: "dress" },
  { category: "clothing", en: "gloves", vi: "Găng tay", dashEn: "gloves" },
  { category: "clothing", en: "handbag", vi: "Túi xách tay", dashEn: "handbag" },
  { category: "clothing", en: "hat", vi: "Mũ", dashEn: "hat" },
  { category: "clothing", en: "high heel shoes", vi: "Giày cao gót", dashEn: "high-heel-shoes" },
  { category: "clothing", en: "hiking boots", vi: "Giày đi bộ", dashEn: "hiking-boots" },
  { category: "clothing", en: "jersey", vi: "Áo đấu", dashEn: "jersey" },
  { category: "clothing", en: "jogger pants", vi: "Quần chạy bộ", dashEn: "jogger-pants" },
  { category: "clothing", en: "necktie", vi: "Cà vạt", dashEn: "necktie" },
  { category: "clothing", en: "pants", vi: "Quần dài", dashEn: "pants" },
  { category: "clothing", en: "ring", vi: "Cái nhẫn", dashEn: "ring" },
  { category: "clothing", en: "sandals", vi: "Cái dép", dashEn: "sandals" },
  { category: "clothing", en: "scarf", vi: "Khăn quàng cổ", dashEn: "scarf" },
  { category: "clothing", en: "shoes", vi: "Cái giày", dashEn: "shoes" },
  { category: "clothing", en: "shorts", vi: "Quần đùi", dashEn: "shorts" },
  { category: "clothing", en: "skirt", vi: "Cái váy", dashEn: "skirt" },
  { category: "clothing", en: "slippers", vi: "Dép", dashEn: "slippers" },
  { category: "clothing", en: "sneakers", vi: "Dày thể thao", dashEn: "sneakers" },
  { category: "clothing", en: "socks", vi: "Cái tất", dashEn: "socks" },
  { category: "clothing", en: "sombrero", vi: "Mũ trùm đầu", dashEn: "sombrero" },
  { category: "clothing", en: "suit", vi: "Bộ đồ", dashEn: "suit" },
  { category: "clothing", en: "sweater", vi: "Áo len", dashEn: "sweater" },
  { category: "clothing", en: "swim shorts", vi: "Quần đùi bơi", dashEn: "swim-shorts" },
  { category: "clothing", en: "t shirt", vi: "Áo cộc tay", dashEn: "t-shirt" },
  { category: "clothing", en: "waist coat", vi: "Áo thắt lưng", dashEn: "waist-coat" },
  { category: "clothing", en: "wallet", vi: "Cái ví", dashEn: "wallet" },
  { category: "clothing", en: "wellington boots", vi: "Ủng cao su", dashEn: "wellington-boots" },
  { category: "clothing", en: "winter hat", vi: "Mũ len", dashEn: "winter-hat" },
  { category: "color", en: "black", vi: "Đen", dashEn: "black" },
  { category: "color", en: "blue", vi: "Xanh da trời", dashEn: "blue" },
  { category: "color", en: "brown", vi: "Nâu", dashEn: "brown" },
  { category: "color", en: "green", vi: "Xanh lá cây", dashEn: "green" },
  { category: "color", en: "grey", vi: "Xám", dashEn: "grey" },
  { category: "color", en: "navy", vi: "Xanh nước biển", dashEn: "navy" },
  { category: "color", en: "pink", vi: "Hồng", dashEn: "pink" },
  { category: "color", en: "purple", vi: "Tím", dashEn: "purple" },
  { category: "color", en: "red", vi: "Đỏ", dashEn: "red" },
  { category: "color", en: "silver", vi: "Bạc", dashEn: "silver" },
  { category: "color", en: "turquoise", vi: "Màu ngọc lam", dashEn: "turquoise" },
  { category: "color", en: "white", vi: "Trắng", dashEn: "white" },
  { category: "color", en: "yellow", vi: "Vàng", dashEn: "yellow" },
  { category: "day", en: "friday", vi: "Thứ sáu", dashEn: "friday" },
  { category: "day", en: "monday", vi: "Thứ hai", dashEn: "monday" },
  { category: "day", en: "saturday", vi: "Thứ bảy", dashEn: "saturday" },
  { category: "day", en: "sunday", vi: "Chủ nhật", dashEn: "sunday" },
  { category: "day", en: "thursday", vi: "Thứ năm", dashEn: "thursday" },
  { category: "day", en: "tuesday", vi: "Thứ  ba", dashEn: "tuesday" },
  { category: "day", en: "wednesday", vi: "Thứ tư", dashEn: "wednesday" },
  { category: "drink", en: "beer", vi: "Bia", dashEn: "beer" },
  { category: "drink", en: "coffee", vi: "Cà phê", dashEn: "coffee" },
  { category: "drink", en: "cola", vi: "Nước cola", dashEn: "cola" },
  { category: "drink", en: "green tea", vi: "Trà xanh", dashEn: "green-tea" },
  { category: "drink", en: "hot chocolate", vi: "Sô cô la nóng", dashEn: "hot-chocolate" },
  { category: "drink", en: "lemonade", vi: "Nước chanh", dashEn: "lemonade" },
  { category: "drink", en: "milk", vi: "Sữa", dashEn: "milk" },
  { category: "drink", en: "milkshake", vi: "Sữa lắc", dashEn: "milkshake" },
  { category: "drink", en: "soda", vi: "Nước ngọt", dashEn: "soda" },
  { category: "drink", en: "tea", vi: "Trà", dashEn: "tea" },
  { category: "drink", en: "water", vi: "Nước", dashEn: "water" },
  { category: "drink", en: "wine", vi: "Rượu", dashEn: "wine" },
  { category: "family", en: "AUNT", vi: "Cô", dashEn: "AUNT" },
  { category: "family", en: "BROTHER", vi: "Anh trai", dashEn: "BROTHER" },
  { category: "family", en: "DAD", vi: "Bố", dashEn: "DAD" },
  { category: "family", en: "FAMILY", vi: "Gia đình", dashEn: "FAMILY" },
  { category: "family", en: "GRANDFATHER", vi: "Ông", dashEn: "GRANDFATHER" },
  { category: "family", en: "GRANDMOTHER", vi: "Bà", dashEn: "GRANDMOTHER" },
  { category: "family", en: "MOM", vi: "Mẹ", dashEn: "MOM" },
  { category: "family", en: "SISTER", vi: "Chị gái", dashEn: "SISTER" },
  { category: "family", en: "UNCLE", vi: "Chú", dashEn: "UNCLE" },
  { category: "feeling", en: "angry", vi: "Giận dữ", dashEn: "angry" },
  { category: "feeling", en: "happy", vi: "Vui vẻ", dashEn: "happy" },
  { category: "feeling", en: "hungry", vi: "Đói", dashEn: "hungry" },
  { category: "feeling", en: "sad", vi: "Buồn", dashEn: "sad" },
  { category: "feeling", en: "scared", vi: "Sợ hãi", dashEn: "scared" },
  { category: "feeling", en: "thirsty", vi: "Khát", dashEn: "thirsty" },
  { category: "feeling", en: "tired", vi: "Mệt", dashEn: "tired" },
  { category: "food", en: "apple pie", vi: "Bánh táo", dashEn: "apple-pie" },
  { category: "food", en: "bacon", vi: "Thịt nướng", dashEn: "bacon" },
  { category: "food", en: "bread", vi: "Bánh mì", dashEn: "bread" },
  { category: "food", en: "burger", vi: "Bánh mì kẹp thịt", dashEn: "burger" },
  { category: "food", en: "cake", vi: "Bánh ngọt", dashEn: "cake" },
  { category: "food", en: "candy", vi: "Kẹo", dashEn: "candy" },
  { category: "food", en: "cereal", vi: "Ngũ cốc", dashEn: "cereal" },
  { category: "food", en: "cheese", vi: "Phô mai", dashEn: "cheese" },
  { category: "food", en: "chocolate", vi: "Sô cô la", dashEn: "chocolate" },
  { category: "food", en: "cookie", vi: "Bánh quy", dashEn: "cookie" },
  { category: "food", en: "crisp", vi: "Giòn", dashEn: "crisp" },
  { category: "food", en: "croissant", vi: "Bánh sừng bò", dashEn: "croissant" },
  { category: "food", en: "curry", vi: "Cà ri", dashEn: "curry" },
  { category: "food", en: "donut", vi: "Bánh vòng", dashEn: "donut" },
  { category: "food", en: "egg", vi: "Trứng", dashEn: "egg" },
  { category: "food", en: "fries", vi: "Khoai tây chiên", dashEn: "fries" },
  { category: "food", en: "gravy", vi: "Tương cà", dashEn: "gravy" },
  { category: "food", en: "gyoza", vi: "Há cảo", dashEn: "gyoza" },
  { category: "food", en: "ham", vi: "Giăm bông", dashEn: "ham" },
  { category: "food", en: "honey", vi: "Mật ong", dashEn: "honey" },
  { category: "food", en: "hot dog", vi: "Xúc xích", dashEn: "hot-dog" },
  { category: "food", en: "jelly", vi: "Thạch", dashEn: "jelly" },
  { category: "food", en: "mashed potato", vi: "Khoai tây nghiền", dashEn: "mashed-potato" },
  { category: "food", en: "meatballs", vi: "Thịt viên", dashEn: "meatballs" },
  { category: "food", en: "noodles", vi: "Mì", dashEn: "noodles" },
  { category: "food", en: "omelet", vi: "Trứng ốp la", dashEn: "omelet" },
  { category: "food", en: "pancakes", vi: "Bánh xèo", dashEn: "pancakes" },
  { category: "food", en: "pasta", vi: "Mỳ ống", dashEn: "pasta" },
  { category: "food", en: "peanut butter", vi: "Bơ đâu phộng", dashEn: "peanut-butter" },
  { category: "food", en: "pickles", vi: "Dưa muối", dashEn: "pickles" },
  { category: "food", en: "pie", vi: "Bánh", dashEn: "pie" },
  { category: "food", en: "pizza", vi: "Bánh pizza", dashEn: "pizza" },
  { category: "food", en: "popcorn", vi: "Bỏng ngô", dashEn: "popcorn" },
  { category: "food", en: "popsicle", vi: "Kem que", dashEn: "popsicle" },
  { category: "food", en: "pretzel", vi: "Bánh quy xoắn", dashEn: "pretzel" },
  { category: "food", en: "pumpkin pie", vi: "Bánh bí ngô", dashEn: "pumpkin-pie" },
  { category: "food", en: "quesadilla", vi: "Bánh phô mai thịt gà", dashEn: "quesadilla" },
  { category: "food", en: "rice", vi: "Gạo", dashEn: "rice" },
  { category: "food", en: "salad", vi: "Xa lát", dashEn: "salad" },
  { category: "food", en: "sandwich", vi: "Bánh mì sandwich", dashEn: "sandwich" },
  { category: "food", en: "sausage", vi: "Lạp xưởng", dashEn: "sausage" },
  { category: "food", en: "shish kebab", vi: "Thịt nướng xiên", dashEn: "shish-kebab" },
  { category: "food", en: "soup", vi: "Súp", dashEn: "soup" },
  { category: "food", en: "spaghetti", vi: "Mì ống Ý", dashEn: "spaghetti" },
  { category: "food", en: "steak", vi: "Bít tết", dashEn: "steak" },
  { category: "food", en: "stew", vi: "Thịt gầm", dashEn: "stew" },
  { category: "food", en: "sushi", vi: "Sushi", dashEn: "sushi" },
  { category: "food", en: "taco", vi: "Bánh taco", dashEn: "taco" },
  { category: "food", en: "tofu", vi: "Đậu phụ", dashEn: "tofu" },
  { category: "food", en: "tortilla", vi: "Bánh ngô", dashEn: "tortilla" },
  { category: "food", en: "waffles", vi: "Bánh quế", dashEn: "waffles" },
  { category: "food", en: "yogurt", vi: "Sữa chua", dashEn: "yogurt" },
  { category: "fruit", en: "apple", vi: "Táo", dashEn: "apple" },
  { category: "fruit", en: "avocado", vi: "Bơ", dashEn: "avocado" },
  { category: "fruit", en: "banana", vi: "Chuối", dashEn: "banana" },
  { category: "fruit", en: "cherry", vi: "Quả anh đào", dashEn: "cherry" },
  { category: "fruit", en: "coconut", vi: "Dừa", dashEn: "coconut" },
  { category: "fruit", en: "grapefruit", vi: "Bưởi chùm", dashEn: "grapefruit" },
  { category: "fruit", en: "grapes", vi: "Nho", dashEn: "grapes" },
  { category: "fruit", en: "kiwi", vi: "Kiwi", dashEn: "kiwi" },
  { category: "fruit", en: "lemon", vi: "Chanh vàng", dashEn: "lemon" },
  { category: "fruit", en: "lime", vi: "Chanh xanh", dashEn: "lime" },
  { category: "fruit", en: "mango", vi: "Xoài", dashEn: "mango" },
  { category: "fruit", en: "melon", vi: "Dưa gang", dashEn: "melon" },
  { category: "fruit", en: "orange", vi: "Cam", dashEn: "orange" },
  { category: "fruit", en: "papaya", vi: "Đu đủ", dashEn: "papaya" },
  { category: "fruit", en: "peach", vi: "Đào", dashEn: "peach" },
  { category: "fruit", en: "pear", vi: "Lê", dashEn: "pear" },
  { category: "fruit", en: "pineapple", vi: "Dứa", dashEn: "pineapple" },
  { category: "fruit", en: "plum", vi: "Mận", dashEn: "plum" },
  { category: "fruit", en: "pomegranate", vi: "Lựu", dashEn: "pomegranate" },
  { category: "fruit", en: "raspberry", vi: "Quả mâm xôi", dashEn: "raspberry" },
  { category: "fruit", en: "strawberry", vi: "Dâu tây", dashEn: "strawberry" },
  { category: "fruit", en: "watermelon", vi: "Dưa hấu", dashEn: "watermelon" },
  { category: "halloween", en: "black cat", vi: "Mèo đen", dashEn: "black-cat" },
  { category: "halloween", en: "cauldron", vi: "cái vạc", dashEn: "cauldron" },
  { category: "halloween", en: "coffin", vi: "Quan tài", dashEn: "coffin" },
  { category: "halloween", en: "crows", vi: "Quạ", dashEn: "crows" },
  { category: "halloween", en: "death", vi: "Cái chết", dashEn: "death" },
  { category: "halloween", en: "devil", vi: "Ác quỷ", dashEn: "devil" },
  { category: "halloween", en: "ghost", vi: "Hồn ma", dashEn: "ghost" },
  { category: "halloween", en: "grave", vi: "Ngôi môi", dashEn: "grave" },
  { category: "halloween", en: "invisible man", vi: "Người vô hình", dashEn: "invisible-man" },
  { category: "halloween", en: "monster", vi: "Quái vật", dashEn: "monster" },
  { category: "halloween", en: "mummy", vi: "Xác ướp", dashEn: "mummy" },
  { category: "halloween", en: "skeleton", vi: "Bộ xương", dashEn: "skeleton" },
  { category: "halloween", en: "skull", vi: "Đầu lâu", dashEn: "skull" },
  { category: "halloween", en: "spider web", vi: "Mạng nhện", dashEn: "spider-web" },
  { category: "halloween", en: "spiders", vi: "Con nhện", dashEn: "spiders" },
  { category: "halloween", en: "vampire", vi: "Ma cà rồng", dashEn: "vampire" },
  { category: "halloween", en: "werewolf", vi: "Ma sói", dashEn: "werewolf" },
  { category: "halloween", en: "witch", vi: "Phù thủy", dashEn: "witch" },
  { category: "halloween", en: "zombie", vi: "Thây ma", dashEn: "zombie" },
  { category: "health", en: "asthma", vi: "Ma bí ngô", dashEn: "asthma" },
  { category: "health", en: "backache", vi: "Đau lưng", dashEn: "backache" },
  { category: "health", en: "broken arm", vi: "Gãy tay", dashEn: "broken-arm" },
  { category: "health", en: "broken leg", vi: "Gãy chân", dashEn: "broken-leg" },
  { category: "health", en: "cough", vi: "Ho", dashEn: "cough" },
  { category: "health", en: "earache", vi: "Đau tai", dashEn: "earache" },
  { category: "health", en: "fever", vi: "Cảm cúm", dashEn: "fever" },
  { category: "health", en: "headache", vi: "Đau đầu", dashEn: "headache" },
  { category: "health", en: "nosebleed", vi: "Chảy máu cam", dashEn: "nosebleed" },
  { category: "health", en: "rash", vi: "Phát ban", dashEn: "rash" },
  { category: "health", en: "runny nose", vi: "Sổ mũi", dashEn: "runny-nose" },
  { category: "health", en: "sneeze", vi: "Hắt hơi", dashEn: "sneeze" },
  { category: "health", en: "sore throat", vi: "Đau họng", dashEn: "sore-throat" },
  { category: "health", en: "stomach ache", vi: "Đau dạ dày", dashEn: "stomach-ache" },
  { category: "health", en: "sun burn", vi: "Cháy nắng", dashEn: "sun-burn" },
  { category: "health", en: "toothache", vi: "Đau răng", dashEn: "toothache" },
  { category: "house", en: "attic", vi: "Gác xép", dashEn: "attic" },
  { category: "house", en: "basement", vi: "Tầng hầm", dashEn: "basement" },
  { category: "house", en: "bathroom", vi: "Phòng tắm", dashEn: "bathroom" },
  { category: "house", en: "bedroom", vi: "Phòng ngủ", dashEn: "bedroom" },
  { category: "house", en: "dining room", vi: "Phòng ăn", dashEn: "dining-room" },
  { category: "house", en: "garage", vi: "Gara để xe", dashEn: "garage" },
  { category: "house", en: "garden", vi: "Vườn", dashEn: "garden" },
  { category: "house", en: "hallway", vi: "Hành lang", dashEn: "hallway" },
  { category: "house", en: "house", vi: "Ngôi nhà", dashEn: "house" },
  { category: "house", en: "laundry room", vi: "Phòng giặt", dashEn: "laundry-room" },
  { category: "kitchen", en: "blender", vi: "Máy xay", dashEn: "blender" },
  { category: "kitchen", en: "bowl", vi: "Cái bát", dashEn: "bowl" },
  { category: "kitchen", en: "bread bin", vi: "Thùng bánh mì", dashEn: "bread-bin" },
  { category: "kitchen", en: "can opener", vi: "Mở nắp chai", dashEn: "can-opener" },
  { category: "kitchen", en: "chopsticks", vi: "Đũa", dashEn: "chopsticks" },
  { category: "kitchen", en: "coffee maker", vi: "Dụng cụ pha cà phê", dashEn: "coffee-maker" },
  { category: "kitchen", en: "colander", vi: "Cái chao", dashEn: "colander" },
  { category: "kitchen", en: "cup", vi: "Cốc", dashEn: "cup" },
  { category: "kitchen", en: "cutting board", vi: "Cái thớt", dashEn: "cutting-board" },
  { category: "kitchen", en: "dishwasher", vi: "Máy rửa bát", dashEn: "dishwasher" },
  { category: "kitchen", en: "dryer", vi: "Máy sấy", dashEn: "dryer" },
  { category: "kitchen", en: "faucet", vi: "Vòi nước", dashEn: "faucet" },
  { category: "kitchen", en: "fork", vi: "Cái dĩa", dashEn: "fork" },
  { category: "kitchen", en: "freezer", vi: "Tủ đông", dashEn: "freezer" },
  { category: "kitchen", en: "grater", vi: "Cái nạo", dashEn: "grater" },
  { category: "kitchen", en: "kettle", vi: "Ấm đun nước", dashEn: "kettle" },
  { category: "kitchen", en: "kitchen counter", vi: "Kệ nhà bếp", dashEn: "kitchen-counter" },
  { category: "kitchen", en: "kitchen", vi: "Bếp", dashEn: "kitchen" },
  { category: "kitchen", en: "knife", vi: "Dao", dashEn: "knife" },
  { category: "kitchen", en: "ladle", vi: "Môi múc canh", dashEn: "ladle" },
  { category: "kitchen", en: "measuring mug", vi: "Cốc đo lường", dashEn: "measuring-mug" },
  { category: "kitchen", en: "microwave", vi: "Lò vi sóng", dashEn: "microwave" },
  { category: "kitchen", en: "mug", vi: "cái ca", dashEn: "mug" },
  { category: "kitchen", en: "oven glove", vi: "Găng tay lò nướng", dashEn: "oven-glove" },
  { category: "kitchen", en: "oven", vi: "Cái lò", dashEn: "oven" },
  { category: "kitchen", en: "pan", vi: "Chảo", dashEn: "pan" },
  { category: "kitchen", en: "plate", vi: "Đĩa", dashEn: "plate" },
  { category: "kitchen", en: "pot", vi: "Nồi", dashEn: "pot" },
  { category: "kitchen", en: "refrigerator", vi: "Tủ lạnh", dashEn: "refrigerator" },
  { category: "kitchen", en: "rolling pin", vi: "Con lăn", dashEn: "rolling-pin" },
  { category: "kitchen", en: "sink", vi: "Chậu rửa", dashEn: "sink" },
  { category: "kitchen", en: "spoon", vi: "Cái thìa", dashEn: "spoon" },
  { category: "kitchen", en: "tea cup", vi: "Cốc uống chè", dashEn: "tea-cup" },
  { category: "kitchen", en: "teapot", vi: "Ấm chè", dashEn: "teapot" },
  { category: "kitchen", en: "toaster", vi: "Máy nướng bánh", dashEn: "toaster" },
  { category: "kitchen", en: "trash can", vi: "Thùng rác", dashEn: "trash-can" },
  { category: "kitchen", en: "washing machine", vi: "Máy giặt", dashEn: "washing-machine" },
  { category: "kitchen", en: "whisk", vi: "Đánh kem", dashEn: "whisk" },
  { category: "kitchen", en: "wooden spoon", vi: "Thìa gỗ", dashEn: "wooden-spoon" },
  { category: "living-room", en: "armchair", vi: "Ghế bành", dashEn: "armchair" },
  { category: "living-room", en: "bookcase", vi: "Kệ sách", dashEn: "bookcase" },
  { category: "living-room", en: "carpet", vi: "Thảm", dashEn: "carpet" },
  { category: "living-room", en: "chair", vi: "Cái ghế", dashEn: "chair" },
  { category: "living-room", en: "coffee table", vi: "Bàn cà phê", dashEn: "coffee-table" },
  { category: "living-room", en: "curtains", vi: "Rèm cửa", dashEn: "curtains" },
  { category: "living-room", en: "cushion", vi: "Cái gối", dashEn: "cushion" },
  { category: "living-room", en: "door", vi: "Cửa ra vào", dashEn: "door" },
  { category: "living-room", en: "fireplace", vi: "Lò sưởi", dashEn: "fireplace" },
  { category: "living-room", en: "lamp", vi: "Cái đèn", dashEn: "lamp" },
  { category: "living-room", en: "laptop", vi: "Máy tính xách tay", dashEn: "laptop" },
  { category: "living-room", en: "living room", vi: "Phòng khách", dashEn: "living-room" },
  { category: "living-room", en: "plant", vi: "Thực vật", dashEn: "plant" },
  { category: "living-room", en: "rug", vi: "Tấm thảm", dashEn: "rug" },
  { category: "living-room", en: "shelf", vi: "Kệ", dashEn: "shelf" },
  { category: "living-room", en: "sofa", vi: "Ghế dài", dashEn: "sofa" },
  { category: "living-room", en: "table", vi: "Cái bàn", dashEn: "table" },
  { category: "living-room", en: "telephone", vi: "Điện thoại di động", dashEn: "telephone" },
  { category: "living-room", en: "vase", vi: "Lọ cắm hoa", dashEn: "vase" },
  { category: "living-room", en: "window", vi: "Cửa sổ", dashEn: "window" },
  { category: "month", en: "april", vi: "Tháng 4", dashEn: "april" },
  { category: "month", en: "august", vi: "Tháng 8", dashEn: "august" },
  { category: "month", en: "december", vi: "Tháng 12", dashEn: "december" },
  { category: "month", en: "january", vi: "Tháng 1", dashEn: "january" },
  { category: "month", en: "february", vi: "Tháng 2 ", dashEn: "february" },
  { category: "month", en: "july", vi: "Tháng 7", dashEn: "july" },
  { category: "month", en: "june", vi: "Tháng 6", dashEn: "june" },
  { category: "month", en: "march", vi: "Tháng 3", dashEn: "march" },
  { category: "month", en: "may", vi: "Tháng 5", dashEn: "may" },
  { category: "month", en: "november", vi: "Tháng 11", dashEn: "november" },
  { category: "month", en: "october", vi: "Tháng 10", dashEn: "october" },
  { category: "month", en: "september", vi: "Tháng 9", dashEn: "september" },
  { category: "occupations", en: "archeologist", vi: "Nhà khảo cổ học", dashEn: "archeologist" },
  { category: "occupations", en: "artist", vi: "Nghệ sĩ", dashEn: "artist" },
  { category: "occupations", en: "ballerina", vi: "Nữ bale", dashEn: "ballerina" },
  { category: "occupations", en: "barber", vi: "Thợ cắt tóc", dashEn: "barber" },
  { category: "occupations", en: "beautician", vi: "Chuyên gia sắc đẹp", dashEn: "beautician" },
  { category: "occupations", en: "builder", vi: "Thợ xây", dashEn: "builder" },
  { category: "occupations", en: "cashier", vi: "Thu ngân", dashEn: "cashier" },
  { category: "occupations", en: "chef", vi: "Đầu bếp", dashEn: "chef" },
  { category: "occupations", en: "cleaner", vi: "Người quét dọn", dashEn: "cleaner" },
  { category: "occupations", en: "clown", vi: "Chú hề", dashEn: "clown" },
  { category: "occupations", en: "dentist", vi: "Bác sĩ nha khoa", dashEn: "dentist" },
  { category: "occupations", en: "doctor", vi: "Bác sĩ", dashEn: "doctor" },
  { category: "occupations", en: "farmer", vi: "Nông dân", dashEn: "farmer" },
  { category: "occupations", en: "firefighter", vi: "Lính cứu hỏa", dashEn: "firefighter" },
  {
    category: "occupations",
    en: "fitness instructor",
    vi: "Huấn luyện viên thể hình",
    dashEn: "fitness-instructor",
  },
  { category: "occupations", en: "florist", vi: "Người bán hoa", dashEn: "florist" },
  { category: "occupations", en: "football player", vi: "Cầu thủ", dashEn: "football-player" },
  { category: "occupations", en: "gardener", vi: "Người làm vườn", dashEn: "gardener" },
  {
    category: "occupations",
    en: "helicopter pilot",
    vi: "Phi công máy bay trực thăng",
    dashEn: "helicopter-pilot",
  },
  { category: "occupations", en: "miner", vi: "Thợ mỏ", dashEn: "miner" },
  { category: "occupations", en: "movie director", vi: "Đạo diễn phim", dashEn: "movie-director" },
  { category: "occupations", en: "nurse", vi: "Y tá", dashEn: "nurse" },
  { category: "occupations", en: "pilot", vi: "Phi công", dashEn: "pilot" },
  { category: "occupations", en: "plumber", vi: "Thợ sửa ống nước", dashEn: "plumber" },
  { category: "occupations", en: "police officer", vi: "Cảnh sát", dashEn: "police-officer" },
  { category: "occupations", en: "race car driver", vi: "Tay đua xe", dashEn: "race-car-driver" },
  { category: "occupations", en: "scientist", vi: "Nhà khoa học", dashEn: "scientist" },
  { category: "occupations", en: "scuba diver", vi: "Thợ lặn", dashEn: "scuba-diver" },
  { category: "occupations", en: "sheriff", vi: "Cảnh sát trưởng", dashEn: "sheriff" },
  { category: "occupations", en: "soldier", vi: "Người lính", dashEn: "soldier" },
  { category: "occupations", en: "surgeon", vi: "Bác sĩ phẫu thuật", dashEn: "surgeon" },
  { category: "occupations", en: "taxi driver", vi: "Tài xế taxi", dashEn: "taxi-driver" },
  { category: "occupations", en: "train driver", vi: "Người lái tàu", dashEn: "train-driver" },
  { category: "occupations", en: "veterinarian", vi: "Bác sĩ thú y", dashEn: "veterinarian" },
  { category: "occupations", en: "waiter", vi: "Bồi bàn nam", dashEn: "waiter" },
  { category: "occupations", en: "welder", vi: "Thợ hàn", dashEn: "welder" },
  { category: "party", en: "balloons", vi: "Bóng bay", dashEn: "balloons" },
  { category: "party", en: "birthday cake", vi: "Bánh sinh nhật", dashEn: "birthday-cake" },
  { category: "party", en: "birthday hat", vi: "Mũ sinh nhật", dashEn: "birthday-hat" },
  { category: "party", en: "candles", vi: "Nến", dashEn: "candles" },
  { category: "party", en: "guests", vi: "Khách mời", dashEn: "guests" },
  { category: "party", en: "music", vi: "Âm nhạc", dashEn: "music" },
  { category: "party", en: "party", vi: "Bữa tiệc", dashEn: "party" },
  { category: "party", en: "present", vi: "Món quà", dashEn: "present" },
  { category: "place", en: "airport", vi: "Sân bay", dashEn: "airport" },
  { category: "place", en: "apartment", vi: "Căn hộ", dashEn: "apartment" },
  { category: "place", en: "arctic", vi: "Bắc cực", dashEn: "arctic" },
  { category: "place", en: "bank", vi: "Ngân hàng", dashEn: "bank" },
  { category: "place", en: "barbershop", vi: "Tiệm cắt tóc", dashEn: "barbershop" },
  { category: "place", en: "beach", vi: "Bãi biển", dashEn: "beach" },
  { category: "place", en: "book store", vi: "Cửa hàng sách", dashEn: "book-store" },
  {
    category: "place",
    en: "burger restaurant",
    vi: "Nhà hàng burger",
    dashEn: "burger-restaurant",
  },
  { category: "place", en: "church", vi: "Nhà thờ", dashEn: "church" },
  { category: "place", en: "circus", vi: "Rạp xiếc", dashEn: "circus" },
  { category: "place", en: "city", vi: "Thành phố", dashEn: "city" },
  { category: "place", en: "clinic", vi: "Phòng khám", dashEn: "clinic" },
  { category: "place", en: "clothes store", vi: "Cửa hàng quần áo", dashEn: "clothes-store" },
  { category: "place", en: "coffee shop", vi: "Cửa hàng cà phê", dashEn: "coffee-shop" },
  { category: "place", en: "desert", vi: "Sa mạc", dashEn: "desert" },
  { category: "place", en: "factory", vi: "Nhà máy", dashEn: "factory" },
  { category: "place", en: "fire station", vi: "Trạm cứu hỏa", dashEn: "fire-station" },
  { category: "place", en: "forest", vi: "Rừng", dashEn: "forest" },
  { category: "place", en: "gas station", vi: "Trạm xăng", dashEn: "gas-station" },
  { category: "place", en: "highway", vi: "Cao tốc", dashEn: "highway" },
  { category: "place", en: "hospital", vi: "Bệnh viện", dashEn: "hospital" },
  { category: "place", en: "hotel", vi: "Khách sạn", dashEn: "hotel" },
  { category: "place", en: "mountains", vi: "Núi", dashEn: "mountains" },
  { category: "place", en: "movie theater", vi: "Rạp phim", dashEn: "movie-theater" },
  { category: "place", en: "museum", vi: "Bảo tàng", dashEn: "museum" },
  { category: "place", en: "park", vi: "Công viên", dashEn: "park" },
  { category: "place", en: "pharmacy", vi: "Hiệu thuốc", dashEn: "pharmacy" },
  { category: "place", en: "police station", vi: "Đồn cảnh sát", dashEn: "police-station" },
  { category: "place", en: "post office", vi: "Bưu cục", dashEn: "post-office" },
  { category: "place", en: "restaurant", vi: "Nhà hàng", dashEn: "restaurant" },
  { category: "place", en: "school", vi: "Trường học", dashEn: "school" },
  { category: "place", en: "sea", vi: "Biển", dashEn: "sea" },
  { category: "place", en: "store", vi: "Cửa hàng", dashEn: "store" },
  { category: "place", en: "supermarket", vi: "Siêu thị", dashEn: "supermarket" },
  { category: "place", en: "train station", vi: "Ga tàu", dashEn: "train-station" },
  { category: "place", en: "zoo", vi: "Sở thú", dashEn: "zoo" },
  { category: "planet", en: "Astronaut", vi: "Phi hành gia", dashEn: "Astronaut" },
  { category: "planet", en: "Earth", vi: "Trái đất", dashEn: "Earth" },
  { category: "planet", en: "Jupiter", vi: "Sao mộc", dashEn: "Jupiter" },
  { category: "planet", en: "Mars", vi: "Sao hỏa", dashEn: "Mars" },
  { category: "planet", en: "Mercury", vi: "Sao thủy", dashEn: "Mercury" },
  { category: "planet", en: "Neptune", vi: "Sao hải vương", dashEn: "Neptune" },
  { category: "planet", en: "Pluto", vi: "Sao diêm vương", dashEn: "Pluto" },
  { category: "planet", en: "Saturn", vi: "Sao thổ", dashEn: "Saturn" },
  { category: "planet", en: "sun", vi: "Mặt trời", dashEn: "sun" },
  { category: "planet", en: "Uranus", vi: "Sao thiên vương", dashEn: "Uranus" },
  { category: "planet", en: "Venus", vi: "Sao kim", dashEn: "Venus" },
  { category: "planet", en: "alien", vi: "Người ngoài hành tinh", dashEn: "alien" },
  { category: "planet", en: "asteroid", vi: "Tiểu hành tinh", dashEn: "asteroid" },
  { category: "planet", en: "comet", vi: "Sao chổi", dashEn: "comet" },
  { category: "planet", en: "constellation", vi: "Chòm sao", dashEn: "constellation" },
  { category: "planet", en: "meteor", vi: "Thiên thạch", dashEn: "meteor" },
  { category: "planet", en: "moon", vi: "Mặt trăng", dashEn: "moon" },
  { category: "planet", en: "observatory", vi: "Đài quan sát", dashEn: "observatory" },
  { category: "planet", en: "satellite", vi: "Vệ tinh", dashEn: "satellite" },
  { category: "planet", en: "space helmet", vi: "Mũ bảo hiểm không gian", dashEn: "space-helmet" },
  { category: "planet", en: "space shuttle", vi: "Tàu con thoi", dashEn: "space-shuttle" },
  { category: "planet", en: "space station", vi: "Trạm không gian", dashEn: "space-station" },
  { category: "planet", en: "space suit", vi: "Đồ phi hành gia", dashEn: "space-suit" },
  { category: "planet", en: "space", vi: "Không gian", dashEn: "space" },
  { category: "planet", en: "star", vi: "Ngôi sao", dashEn: "star" },
  { category: "planet", en: "telescope", vi: "Kính viễn vọng", dashEn: "telescope" },
  { category: "plant", en: "bark", vi: "Vỏ cây", dashEn: "bark" },
  { category: "plant", en: "branch", vi: "Cành cây", dashEn: "branch" },
  { category: "plant", en: "bush", vi: "Bụi cây", dashEn: "bush" },
  { category: "plant", en: "flower", vi: "Hoa", dashEn: "flower" },
  { category: "plant", en: "leaves", vi: "Lá", dashEn: "leaves" },
  { category: "plant", en: "petal", vi: "Cánh hoa", dashEn: "petal" },
  { category: "plant", en: "rain", vi: "Mưa", dashEn: "rain" },
  { category: "plant", en: "seed", vi: "Hạt giống", dashEn: "seed" },
  { category: "plant", en: "soil", vi: "Đất", dashEn: "soil" },
  { category: "plant", en: "sprout", vi: "Nảy mầm", dashEn: "sprout" },
  { category: "plant", en: "tree roots", vi: "Rễ cây", dashEn: "tree-roots" },
  { category: "plant", en: "tree", vi: "Cây", dashEn: "tree" },
  { category: "plant", en: "trunk", vi: "Thân cây", dashEn: "trunk" },
  { category: "plant", en: "wind", vi: "Gió", dashEn: "wind" },
  { category: "playground", en: "bench", vi: "Băng ghế", dashEn: "bench" },
  {
    category: "playground",
    en: "drink fountain",
    vi: "Dài phun nước uống",
    dashEn: "drink-fountain",
  },
  { category: "playground", en: "jungle gym", vi: "Tập GYM", dashEn: "jungle-gym" },
  { category: "playground", en: "picnic table", vi: "Bàn dã ngoại", dashEn: "picnic-table" },
  { category: "playground", en: "playground", vi: "Sân chơi", dashEn: "playground" },
  { category: "playground", en: "sandbox", vi: "Hộp cát", dashEn: "sandbox" },
  { category: "playground", en: "seesaw", vi: "Bập bênh", dashEn: "seesaw" },
  { category: "playground", en: "slide", vi: "Trượt", dashEn: "slide" },
  { category: "playground", en: "spring rider", vi: "Ngựa lò xo", dashEn: "spring-rider" },
  { category: "playground", en: "swing", vi: "Xích đu", dashEn: "swing" },
  { category: "playground", en: "tunnel", vi: "Đường hầm", dashEn: "tunnel" },
  { category: "playground", en: "zipline", vi: "Đu dây", dashEn: "zipline" },
  { category: "prepositions", en: "above", vi: "Ở trên", dashEn: "above" },
  { category: "prepositions", en: "behind", vi: "Ở đằng sau", dashEn: "behind" },
  { category: "prepositions", en: "below", vi: "Ở dưới", dashEn: "below" },
  { category: "prepositions", en: "in between", vi: "Ở giữa", dashEn: "in-between" },
  { category: "prepositions", en: "in front of", vi: "Ở trước mặt", dashEn: "in-front-of" },
  { category: "prepositions", en: "in", vi: "Ở trong", dashEn: "in" },
  { category: "season", en: "autumn", vi: "Mùa thu", dashEn: "autumn" },
  { category: "season", en: "spring", vi: "Mùa xuân", dashEn: "spring" },
  { category: "season", en: "summer", vi: "Mùa hạ", dashEn: "summer" },
  { category: "season", en: "winter", vi: "Mùa đông", dashEn: "winter" },
  { category: "shape", en: "circle", vi: "Hình tròn", dashEn: "circle" },
  { category: "shape", en: "crescent", vi: "Hình bán nguyệt", dashEn: "crescent" },
  { category: "shape", en: "diamond", vi: "Hình thoi", dashEn: "diamond" },
  { category: "shape", en: "heart", vi: "Hình trái tim", dashEn: "heart" },
  { category: "shape", en: "hexagon", vi: "Hình lục giác", dashEn: "hexagon" },
  { category: "shape", en: "pentagon", vi: "Hình ngũ giác", dashEn: "pentagon" },
  { category: "shape", en: "rectangle", vi: "Hình chữ nhật", dashEn: "rectangle" },
  { category: "shape", en: "square", vi: "Hình vuông", dashEn: "square" },
  { category: "shape", en: "triangle", vi: "Hình tam giác", dashEn: "triangle" },
  { category: "sports", en: "archery", vi: "Bắn cung", dashEn: "archery" },
  { category: "sports", en: "badminton", vi: "Cầu lông", dashEn: "badminton" },
  { category: "sports", en: "baseball", vi: "Bóng chày", dashEn: "baseball" },
  { category: "sports", en: "basketball", vi: "Bóng rổ", dashEn: "basketball" },
  { category: "sports", en: "bowling", vi: "Bóng bowling", dashEn: "bowling" },
  { category: "sports", en: "boxing", vi: "Đấm bốc", dashEn: "boxing" },
  { category: "sports", en: "cycling", vi: "Đạp xe", dashEn: "cycling" },
  { category: "sports", en: "darts", vi: "Phi tiêu", dashEn: "darts" },
  { category: "sports", en: "fencing", vi: "Đấu kiếm", dashEn: "fencing" },
  { category: "sports", en: "fishing", vi: "Câu cá", dashEn: "fishing" },
  { category: "sports", en: "golf", vi: "Đánh gôn", dashEn: "golf" },
  { category: "sports", en: "ice hockey", vi: "Khúc côn cầu trên băng", dashEn: "ice-hockey" },
  { category: "sports", en: "ice skating", vi: "Trượt băng", dashEn: "ice-skating" },
  { category: "sports", en: "inline skating", vi: "Trượt patin", dashEn: "inline-skating" },
  { category: "sports", en: "pool", vi: "Bi-a", dashEn: "pool" },
  { category: "sports", en: "rock climbing", vi: "Leo núi", dashEn: "rock-climbing" },
  { category: "sports", en: "rowing", vi: "Chèo thuyền", dashEn: "rowing" },
  { category: "sports", en: "rugby", vi: "Bóng bầu dục", dashEn: "rugby" },
  { category: "sports", en: "sailing", vi: "Đua thuyền", dashEn: "sailing" },
  { category: "sports", en: "show jumping", vi: "Biểu diễn nhảy", dashEn: "show-jumping" },
  { category: "sports", en: "skiing", vi: "Trượt tuyết", dashEn: "skiing" },
  { category: "sports", en: "soccer", vi: "Bóng đá", dashEn: "soccer" },
  { category: "sports", en: "surfing", vi: "Lướt sóng", dashEn: "surfing" },
  { category: "sports", en: "swimming", vi: "Bơi lội", dashEn: "swimming" },
  { category: "sports", en: "table tennis", vi: "Bóng bàn", dashEn: "table-tennis" },
  { category: "sports", en: "tennis", vi: "Quần vợt", dashEn: "tennis" },
  { category: "sports", en: "volleyball", vi: "Bóng chuyền", dashEn: "volleyball" },
  { category: "sports", en: "wrestling", vi: "Vật", dashEn: "wrestling" },
  { category: "toy", en: "RC car", vi: "Xe đua", dashEn: "RC-car" },
  { category: "toy", en: "baby doll", vi: "Búp bê", dashEn: "baby-doll" },
  { category: "toy", en: "ball", vi: "Quả bóng", dashEn: "ball" },
  { category: "toy", en: "block game", vi: "Đồ chơi hình khối", dashEn: "block-game" },
  { category: "toy", en: "blocks", vi: "Hình khối", dashEn: "blocks" },
  { category: "toy", en: "board game", vi: "Chơi cờ", dashEn: "board-game" },
  { category: "toy", en: "bouncing toy", vi: "Đồ chơi nhảy", dashEn: "bouncing-toy" },
  { category: "toy", en: "building blocks", vi: "Xếp hình", dashEn: "building-blocks" },
  { category: "toy", en: "inline skates", vi: "Giày trượt 1 hàng", dashEn: "inline-skates" },
  { category: "toy", en: "jump rope", vi: "Nhảy dây", dashEn: "jump-rope" },
  { category: "toy", en: "modeling clay", vi: "Đất sét mô hình", dashEn: "modeling-clay" },
  { category: "toy", en: "puzzle", vi: "Câu đố", dashEn: "puzzle" },
  { category: "toy", en: "robot", vi: "Rô bốt", dashEn: "robot" },
  { category: "toy", en: "scooter", vi: "Xe tay ga", dashEn: "scooter" },
  { category: "toy", en: "skateboard", vi: "Ván trượt", dashEn: "skateboard" },
  { category: "toy", en: "swimming pool", vi: "Hồ bơi", dashEn: "swimming-pool" },
  { category: "toy", en: "tablet", vi: "Bảng viết", dashEn: "tablet" },
  { category: "toy", en: "toy car", vi: "Xe đồ chơi", dashEn: "toy-car" },
  { category: "toy", en: "toy dinosaur", vi: "Khủng long đồ chơi", dashEn: "toy-dinosaur" },
  { category: "toy", en: "toy truck", vi: "Xe tải đồ chơi", dashEn: "toy-truck" },
  { category: "toy", en: "videogame", vi: "Trò chơi điện tử", dashEn: "videogame" },
  { category: "transportation", en: "UFO", vi: "Vật tể bay không xác định", dashEn: "UFO" },
  { category: "transportation", en: "aeroplane", vi: "Tàu vũ trụ", dashEn: "aeroplane" },
  { category: "transportation", en: "ambulance", vi: "Xe cứu thương", dashEn: "ambulance" },
  { category: "transportation", en: "bicycle", vi: "Xe đạp", dashEn: "bicycle" },
  { category: "transportation", en: "boat", vi: "Thuyền", dashEn: "boat" },
  { category: "transportation", en: "buggy", vi: "Xe lôi", dashEn: "buggy" },
  { category: "transportation", en: "bus", vi: "Xe buýt", dashEn: "bus" },
  { category: "transportation", en: "camper van", vi: "Xe cắm trại", dashEn: "camper-van" },
  { category: "transportation", en: "car", vi: "Xe ô tô", dashEn: "car" },
  { category: "transportation", en: "cement truck", vi: "Xe chở xi măng", dashEn: "cement-truck" },
  { category: "transportation", en: "crane", vi: "Cầu trục", dashEn: "crane" },
  { category: "transportation", en: "cruise boat", vi: "Du thuyền", dashEn: "cruise-boat" },
  { category: "transportation", en: "ferry", vi: "Phà", dashEn: "ferry" },
  { category: "transportation", en: "fire engine", vi: "Xe cứu hỏa", dashEn: "fire-engine" },
  { category: "transportation", en: "forklift", vi: "Xe nâng", dashEn: "forklift" },
  { category: "transportation", en: "garbage truck", vi: "Xe chở rác", dashEn: "garbage-truck" },
  { category: "transportation", en: "helicopter", vi: "Máy bay trực thăng", dashEn: "helicopter" },
  {
    category: "transportation",
    en: "hot air balloon",
    vi: "Khinh khí cầu",
    dashEn: "hot-air-balloon",
  },
  {
    category: "transportation",
    en: "jet ski",
    vi: "Máy bay phản lực trượt tuyết",
    dashEn: "jet-ski",
  },
  {
    category: "transportation",
    en: "monster truck",
    vi: "Xe tải quái vật",
    dashEn: "monster-truck",
  },
  { category: "transportation", en: "motorcycle", vi: "Xe máy", dashEn: "motorcycle" },
  { category: "transportation", en: "pick up truck", vi: "Xe bán tải", dashEn: "pick-up-truck" },
  { category: "transportation", en: "pirate ship", vi: "Thuyền cướp biển", dashEn: "pirate-ship" },
  { category: "transportation", en: "police car", vi: "Xe cảnh sát", dashEn: "police-car" },
  { category: "transportation", en: "rocket", vi: "Tên lửa", dashEn: "rocket" },
  { category: "transportation", en: "speedboat", vi: "Tàu cao tốc", dashEn: "speedboat" },
  { category: "transportation", en: "submarine", vi: "Tàu ngầm", dashEn: "submarine" },
  { category: "transportation", en: "subway", vi: "Tàu điện ngầm", dashEn: "subway" },
  { category: "transportation", en: "tank", vi: "Xe tăng", dashEn: "tank" },
  { category: "transportation", en: "tractor", vi: "Máy kéo", dashEn: "tractor" },
  { category: "transportation", en: "train", vi: "Tàu", dashEn: "train" },
  { category: "transportation", en: "tricycle", vi: "Xe ba bánh", dashEn: "tricycle" },
  { category: "transportation", en: "truck", vi: "Xe tải", dashEn: "truck" },
  { category: "transportation", en: "unicycle", vi: "Xe đạp 1 bánh", dashEn: "unicycle" },
  { category: "transportation", en: "wagon", vi: "Toa xe", dashEn: "wagon" },
  { category: "vegetable", en: "asparagus", vi: "Măng tây", dashEn: "asparagus" },
  { category: "vegetable", en: "beans", vi: "Đậu", dashEn: "beans" },
  { category: "vegetable", en: "beets", vi: "củ dền", dashEn: "beets" },
  { category: "vegetable", en: "broccoli", vi: "Bông cải xanh", dashEn: "broccoli" },
  { category: "vegetable", en: "cabbage", vi: "Bắp cải", dashEn: "cabbage" },
  { category: "vegetable", en: "carrot", vi: "Cà rốt", dashEn: "carrot" },
  { category: "vegetable", en: "cauliflower", vi: "Xúp lơ trắng", dashEn: "cauliflower" },
  { category: "vegetable", en: "chilli", vi: "Ớt", dashEn: "chilli" },
  { category: "vegetable", en: "corn", vi: "Ngô", dashEn: "corn" },
  { category: "vegetable", en: "cucumber", vi: "Dưa chuột", dashEn: "cucumber" },
  { category: "vegetable", en: "eggplant", vi: "Cà tím", dashEn: "eggplant" },
  { category: "vegetable", en: "garlic", vi: "Tỏi", dashEn: "garlic" },
  { category: "vegetable", en: "leek", vi: "Tỏi tây", dashEn: "leek" },
  { category: "vegetable", en: "lettuce", vi: "Rau xa lách", dashEn: "lettuce" },
  { category: "vegetable", en: "mushroom", vi: "Nấm", dashEn: "mushroom" },
  { category: "vegetable", en: "onion", vi: "Hành tây", dashEn: "onion" },
  { category: "vegetable", en: "pepper", vi: "Hat tiêu", dashEn: "pepper" },
  { category: "vegetable", en: "potato", vi: "Khoai tây", dashEn: "potato" },
  { category: "vegetable", en: "pumpkin", vi: "Bí ngô", dashEn: "pumpkin" },
  { category: "vegetable", en: "raddish", vi: "Củ cải", dashEn: "raddish" },
  { category: "vegetable", en: "spinach", vi: "Rau chân vịt", dashEn: "spinach" },
  { category: "vegetable", en: "sproats", vi: "Rau mầm", dashEn: "sproats" },
  { category: "vegetable", en: "sweet potato", vi: "Khoai lang", dashEn: "sweet-potato" },
  { category: "vegetable", en: "tomato", vi: "Cà chua", dashEn: "tomato" },
  { category: "verb", en: "brush", vi: "Chải", dashEn: "brush" },
  { category: "verb", en: "build", vi: "Xây", dashEn: "build" },
  { category: "verb", en: "catch", vi: "Bắt lấy", dashEn: "catch" },
  { category: "verb", en: "climb", vi: "Leo", dashEn: "climb" },
  { category: "verb", en: "close", vi: "Đóng vào", dashEn: "close" },
  { category: "verb", en: "cook", vi: "Nấu ăn", dashEn: "cook" },
  { category: "verb", en: "cut", vi: "Cắt", dashEn: "cut" },
  { category: "verb", en: "draw", vi: "Vẽ", dashEn: "draw" },
  { category: "verb", en: "drive", vi: "Lái xe", dashEn: "drive" },
  { category: "verb", en: "fix", vi: "Sửa", dashEn: "fix" },
  { category: "verb", en: "give", vi: "Cho", dashEn: "give" },
  { category: "verb", en: "go to", vi: "Đi đến", dashEn: "go-to" },
  { category: "verb", en: "have", vi: "Có", dashEn: "have" },
  { category: "verb", en: "kick", vi: "Đá", dashEn: "kick" },
  { category: "verb", en: "like", vi: "Thích", dashEn: "like" },
  { category: "verb", en: "love", vi: "Yêu", dashEn: "love" },
  { category: "verb", en: "make", vi: "Làm", dashEn: "make" },
  { category: "verb", en: "mix", vi: "Trộn", dashEn: "mix" },
  { category: "verb", en: "open", vi: "Mở", dashEn: "open" },
  { category: "verb", en: "paint", vi: "Sơn", dashEn: "paint" },
  { category: "verb", en: "pull", vi: "Kéo", dashEn: "pull" },
  { category: "verb", en: "punch", vi: "Đấm", dashEn: "punch" },
  { category: "verb", en: "push", vi: "Đẩy", dashEn: "push" },
  { category: "verb", en: "see", vi: "Nhìn", dashEn: "see" },
  { category: "verb", en: "sit", vi: "Ngồi", dashEn: "sit" },
  { category: "verb", en: "stand", vi: "Đứng", dashEn: "stand" },
  { category: "verb", en: "study", vi: "Học", dashEn: "study" },
  { category: "verb", en: "take", vi: "Lấy", dashEn: "take" },
  { category: "verb", en: "talk", vi: "Nói chuyện", dashEn: "talk" },
  { category: "verb", en: "tell", vi: "Nói", dashEn: "tell" },
  { category: "verb", en: "think", vi: "Nghĩ", dashEn: "think" },
  { category: "verb", en: "throw", vi: "Ném", dashEn: "throw" },
  { category: "verb", en: "tie", vi: "Buộc", dashEn: "tie" },
  { category: "verb", en: "turn off", vi: "Tắt", dashEn: "turn-off" },
  { category: "verb", en: "turn on", vi: "Bật", dashEn: "turn-on" },
  { category: "verb", en: "want", vi: "Muốn", dashEn: "want" },
  { category: "verb", en: "wash", vi: "Rửa", dashEn: "wash" },
  { category: "verb", en: "watch", vi: "Xem", dashEn: "watch" },
  { category: "verb", en: "wear", vi: "Mặc", dashEn: "wear" },
  { category: "verb", en: "write", vi: "Viết", dashEn: "write" },
  { category: "weather", en: "cloudy", vi: "Nhiều mây", dashEn: "cloudy" },
  { category: "weather", en: "rainy", vi: "có mưa", dashEn: "rainy" },
  { category: "weather", en: "snowy", vi: "Tuyết rơi", dashEn: "snowy" },
  { category: "weather", en: "stormy", vi: "Bão", dashEn: "stormy" },
  { category: "weather", en: "sunny", vi: "Nắng", dashEn: "sunny" },
  { category: "weather", en: "windy", vi: "có gió", dashEn: "windy" },
]
