interface Word {
  en: string
  viSound: number
  enSound: number
  image: number
}

export const words: Word[] = [
  {
    en: "climbing",
    viSound: require("assets/audio/activity/vi/climbing.wav"),
    enSound: require("assets/audio/activity/en/climbing.wav"),
    image: require("assets/images/activity/climbing.jpg"),
  },
  {
    en: "cooking",
    viSound: require("assets/audio/activity/vi/cooking.wav"),
    enSound: require("assets/audio/activity/en/cooking.wav"),
    image: require("assets/images/activity/cooking.jpg"),
  },
  {
    en: "dancing",
    viSound: require("assets/audio/activity/vi/dancing.wav"),
    enSound: require("assets/audio/activity/en/dancing.wav"),
    image: require("assets/images/activity/dancing.jpg"),
  },
  {
    en: "drinking",
    viSound: require("assets/audio/activity/vi/drinking.wav"),
    enSound: require("assets/audio/activity/en/drinking.wav"),
    image: require("assets/images/activity/drinking.jpg"),
  },
  {
    en: "eating",
    viSound: require("assets/audio/activity/vi/eating.wav"),
    enSound: require("assets/audio/activity/en/eating.wav"),
    image: require("assets/images/activity/eating.jpg"),
  },
  {
    en: "hiking",
    viSound: require("assets/audio/activity/vi/hiking.wav"),
    enSound: require("assets/audio/activity/en/hiking.wav"),
    image: require("assets/images/activity/hiking.jpg"),
  },
  {
    en: "jogging",
    viSound: require("assets/audio/activity/vi/jogging.wav"),
    enSound: require("assets/audio/activity/en/jogging.wav"),
    image: require("assets/images/activity/jogging.jpg"),
  },
  {
    en: "playing",
    viSound: require("assets/audio/activity/vi/playing.wav"),
    enSound: require("assets/audio/activity/en/playing.wav"),
    image: require("assets/images/activity/playing.jpg"),
  },
  {
    en: "reading",
    viSound: require("assets/audio/activity/vi/reading.wav"),
    enSound: require("assets/audio/activity/en/reading.wav"),
    image: require("assets/images/activity/reading.jpg"),
  },
  {
    en: "riding",
    viSound: require("assets/audio/activity/vi/riding.wav"),
    enSound: require("assets/audio/activity/en/riding.wav"),
    image: require("assets/images/activity/riding.jpg"),
  },
  {
    en: "running",
    viSound: require("assets/audio/activity/vi/running.wav"),
    enSound: require("assets/audio/activity/en/running.wav"),
    image: require("assets/images/activity/running.jpg"),
  },
  {
    en: "singing",
    viSound: require("assets/audio/activity/vi/singing.wav"),
    enSound: require("assets/audio/activity/en/singing.wav"),
    image: require("assets/images/activity/singing.jpg"),
  },
  {
    en: "sleeping",
    viSound: require("assets/audio/activity/vi/sleeping.wav"),
    enSound: require("assets/audio/activity/en/sleeping.wav"),
    image: require("assets/images/activity/sleeping.jpg"),
  },
  {
    en: "studying",
    viSound: require("assets/audio/activity/vi/studying.wav"),
    enSound: require("assets/audio/activity/en/studying.wav"),
    image: require("assets/images/activity/studying.jpg"),
  },
  {
    en: "watching-TV",
    viSound: require("assets/audio/activity/vi/watching-TV.wav"),
    enSound: require("assets/audio/activity/en/watching-TV.wav"),
    image: require("assets/images/activity/watching-TV.jpg"),
  },
  {
    en: "bad",
    viSound: require("assets/audio/adjective/vi/bad.wav"),
    enSound: require("assets/audio/adjective/en/bad.wav"),
    image: require("assets/images/adjective/bad.jpg"),
  },
  {
    en: "beautiful",
    viSound: require("assets/audio/adjective/vi/beautiful.wav"),
    enSound: require("assets/audio/adjective/en/beautiful.wav"),
    image: require("assets/images/adjective/beautiful.jpg"),
  },
  {
    en: "big",
    viSound: require("assets/audio/adjective/vi/big.wav"),
    enSound: require("assets/audio/adjective/en/big.wav"),
    image: require("assets/images/adjective/big.jpg"),
  },
  {
    en: "bitter",
    viSound: require("assets/audio/adjective/vi/bitter.wav"),
    enSound: require("assets/audio/adjective/en/bitter.wav"),
    image: require("assets/images/adjective/bitter.jpg"),
  },
  {
    en: "bright",
    viSound: require("assets/audio/adjective/vi/bright.wav"),
    enSound: require("assets/audio/adjective/en/bright.wav"),
    image: require("assets/images/adjective/bright.jpg"),
  },
  {
    en: "cheap",
    viSound: require("assets/audio/adjective/vi/cheap.wav"),
    enSound: require("assets/audio/adjective/en/cheap.wav"),
    image: require("assets/images/adjective/cheap.jpg"),
  },
  {
    en: "clean",
    viSound: require("assets/audio/adjective/vi/clean.wav"),
    enSound: require("assets/audio/adjective/en/clean.wav"),
    image: require("assets/images/adjective/clean.jpg"),
  },
  {
    en: "cold",
    viSound: require("assets/audio/adjective/vi/cold.wav"),
    enSound: require("assets/audio/adjective/en/cold.wav"),
    image: require("assets/images/adjective/cold.jpg"),
  },
  {
    en: "dark",
    viSound: require("assets/audio/adjective/vi/dark.wav"),
    enSound: require("assets/audio/adjective/en/dark.wav"),
    image: require("assets/images/adjective/dark.jpg"),
  },
  {
    en: "day",
    viSound: require("assets/audio/adjective/vi/day.wav"),
    enSound: require("assets/audio/adjective/en/day.wav"),
    image: require("assets/images/adjective/day.jpg"),
  },
  {
    en: "deep",
    viSound: require("assets/audio/adjective/vi/deep.wav"),
    enSound: require("assets/audio/adjective/en/deep.wav"),
    image: require("assets/images/adjective/deep.jpg"),
  },
  {
    en: "dirty",
    viSound: require("assets/audio/adjective/vi/dirty.wav"),
    enSound: require("assets/audio/adjective/en/dirty.wav"),
    image: require("assets/images/adjective/dirty.jpg"),
  },
  {
    en: "dry",
    viSound: require("assets/audio/adjective/vi/dry.wav"),
    enSound: require("assets/audio/adjective/en/dry.wav"),
    image: require("assets/images/adjective/dry.jpg"),
  },
  {
    en: "empty",
    viSound: require("assets/audio/adjective/vi/empty.wav"),
    enSound: require("assets/audio/adjective/en/empty.wav"),
    image: require("assets/images/adjective/empty.jpg"),
  },
  {
    en: "expensive",
    viSound: require("assets/audio/adjective/vi/expensive.wav"),
    enSound: require("assets/audio/adjective/en/expensive.wav"),
    image: require("assets/images/adjective/expensive.jpg"),
  },
  {
    en: "fast",
    viSound: require("assets/audio/adjective/vi/fast.wav"),
    enSound: require("assets/audio/adjective/en/fast.wav"),
    image: require("assets/images/adjective/fast.jpg"),
  },
  {
    en: "fat",
    viSound: require("assets/audio/adjective/vi/fat.wav"),
    enSound: require("assets/audio/adjective/en/fat.wav"),
    image: require("assets/images/adjective/fat.jpg"),
  },
  {
    en: "few",
    viSound: require("assets/audio/adjective/vi/few.wav"),
    enSound: require("assets/audio/adjective/en/few.wav"),
    image: require("assets/images/adjective/few.jpg"),
  },
  {
    en: "full",
    viSound: require("assets/audio/adjective/vi/full.wav"),
    enSound: require("assets/audio/adjective/en/full.wav"),
    image: require("assets/images/adjective/full.jpg"),
  },
  {
    en: "good",
    viSound: require("assets/audio/adjective/vi/good.wav"),
    enSound: require("assets/audio/adjective/en/good.wav"),
    image: require("assets/images/adjective/good.jpg"),
  },
  {
    en: "hard",
    viSound: require("assets/audio/adjective/vi/hard.wav"),
    enSound: require("assets/audio/adjective/en/hard.wav"),
    image: require("assets/images/adjective/hard.jpg"),
  },
  {
    en: "heavy",
    viSound: require("assets/audio/adjective/vi/heavy.wav"),
    enSound: require("assets/audio/adjective/en/heavy.wav"),
    image: require("assets/images/adjective/heavy.jpg"),
  },
  {
    en: "hot",
    viSound: require("assets/audio/adjective/vi/hot.wav"),
    enSound: require("assets/audio/adjective/en/hot.wav"),
    image: require("assets/images/adjective/hot.jpg"),
  },
  {
    en: "light",
    viSound: require("assets/audio/adjective/vi/light.wav"),
    enSound: require("assets/audio/adjective/en/light.wav"),
    image: require("assets/images/adjective/light.jpg"),
  },
  {
    en: "long",
    viSound: require("assets/audio/adjective/vi/long.wav"),
    enSound: require("assets/audio/adjective/en/long.wav"),
    image: require("assets/images/adjective/long.jpg"),
  },
  {
    en: "many",
    viSound: require("assets/audio/adjective/vi/many.wav"),
    enSound: require("assets/audio/adjective/en/many.wav"),
    image: require("assets/images/adjective/many.jpg"),
  },
  {
    en: "new",
    viSound: require("assets/audio/adjective/vi/new.wav"),
    enSound: require("assets/audio/adjective/en/new.wav"),
    image: require("assets/images/adjective/new.jpg"),
  },
  {
    en: "night",
    viSound: require("assets/audio/adjective/vi/night.wav"),
    enSound: require("assets/audio/adjective/en/night.wav"),
    image: require("assets/images/adjective/night.jpg"),
  },
  {
    en: "noisy",
    viSound: require("assets/audio/adjective/vi/noisy.wav"),
    enSound: require("assets/audio/adjective/en/noisy.wav"),
    image: require("assets/images/adjective/noisy.jpg"),
  },
  {
    en: "old",
    viSound: require("assets/audio/adjective/vi/old.wav"),
    enSound: require("assets/audio/adjective/en/old.wav"),
    image: require("assets/images/adjective/old.jpg"),
  },
  {
    en: "quiet",
    viSound: require("assets/audio/adjective/vi/quiet.wav"),
    enSound: require("assets/audio/adjective/en/quiet.wav"),
    image: require("assets/images/adjective/quiet.jpg"),
  },
  {
    en: "rough",
    viSound: require("assets/audio/adjective/vi/rough.wav"),
    enSound: require("assets/audio/adjective/en/rough.wav"),
    image: require("assets/images/adjective/rough.jpg"),
  },
  {
    en: "shallow",
    viSound: require("assets/audio/adjective/vi/shallow.wav"),
    enSound: require("assets/audio/adjective/en/shallow.wav"),
    image: require("assets/images/adjective/shallow.jpg"),
  },
  {
    en: "short",
    viSound: require("assets/audio/adjective/vi/short.wav"),
    enSound: require("assets/audio/adjective/en/short.wav"),
    image: require("assets/images/adjective/short.jpg"),
  },
  {
    en: "slow",
    viSound: require("assets/audio/adjective/vi/slow.wav"),
    enSound: require("assets/audio/adjective/en/slow.wav"),
    image: require("assets/images/adjective/slow.jpg"),
  },
  {
    en: "small",
    viSound: require("assets/audio/adjective/vi/small.wav"),
    enSound: require("assets/audio/adjective/en/small.wav"),
    image: require("assets/images/adjective/small.jpg"),
  },
  {
    en: "smooth",
    viSound: require("assets/audio/adjective/vi/smooth.wav"),
    enSound: require("assets/audio/adjective/en/smooth.wav"),
    image: require("assets/images/adjective/smooth.jpg"),
  },
  {
    en: "soft",
    viSound: require("assets/audio/adjective/vi/soft.wav"),
    enSound: require("assets/audio/adjective/en/soft.wav"),
    image: require("assets/images/adjective/soft.jpg"),
  },
  {
    en: "strong",
    viSound: require("assets/audio/adjective/vi/strong.wav"),
    enSound: require("assets/audio/adjective/en/strong.wav"),
    image: require("assets/images/adjective/strong.jpg"),
  },
  {
    en: "sweet",
    viSound: require("assets/audio/adjective/vi/sweet.wav"),
    enSound: require("assets/audio/adjective/en/sweet.wav"),
    image: require("assets/images/adjective/sweet.jpg"),
  },
  {
    en: "tall",
    viSound: require("assets/audio/adjective/vi/tall.wav"),
    enSound: require("assets/audio/adjective/en/tall.wav"),
    image: require("assets/images/adjective/tall.jpg"),
  },
  {
    en: "thin",
    viSound: require("assets/audio/adjective/vi/thin.wav"),
    enSound: require("assets/audio/adjective/en/thin.wav"),
    image: require("assets/images/adjective/thin.jpg"),
  },
  {
    en: "ugly",
    viSound: require("assets/audio/adjective/vi/ugly.wav"),
    enSound: require("assets/audio/adjective/en/ugly.wav"),
    image: require("assets/images/adjective/ugly.jpg"),
  },
  {
    en: "weak",
    viSound: require("assets/audio/adjective/vi/weak.wav"),
    enSound: require("assets/audio/adjective/en/weak.wav"),
    image: require("assets/images/adjective/weak.jpg"),
  },
  {
    en: "wet",
    viSound: require("assets/audio/adjective/vi/wet.wav"),
    enSound: require("assets/audio/adjective/en/wet.wav"),
    image: require("assets/images/adjective/wet.jpg"),
  },
  {
    en: "young",
    viSound: require("assets/audio/adjective/vi/young.wav"),
    enSound: require("assets/audio/adjective/en/young.wav"),
    image: require("assets/images/adjective/young.jpg"),
  },
  {
    en: "A",
    viSound: require("assets/audio/alphabet/vi/A.wav"),
    enSound: require("assets/audio/alphabet/en/A.wav"),
    image: require("assets/images/alphabet/A.jpg"),
  },
  {
    en: "B",
    viSound: require("assets/audio/alphabet/vi/B.wav"),
    enSound: require("assets/audio/alphabet/en/B.wav"),
    image: require("assets/images/alphabet/B.jpg"),
  },
  {
    en: "C",
    viSound: require("assets/audio/alphabet/vi/C.wav"),
    enSound: require("assets/audio/alphabet/en/C.wav"),
    image: require("assets/images/alphabet/C.jpg"),
  },
  {
    en: "D",
    viSound: require("assets/audio/alphabet/vi/D.wav"),
    enSound: require("assets/audio/alphabet/en/D.wav"),
    image: require("assets/images/alphabet/D.jpg"),
  },
  {
    en: "E",
    viSound: require("assets/audio/alphabet/vi/E.wav"),
    enSound: require("assets/audio/alphabet/en/E.wav"),
    image: require("assets/images/alphabet/E.jpg"),
  },
  {
    en: "F",
    viSound: require("assets/audio/alphabet/vi/F.wav"),
    enSound: require("assets/audio/alphabet/en/F.wav"),
    image: require("assets/images/alphabet/F.jpg"),
  },
  {
    en: "G",
    viSound: require("assets/audio/alphabet/vi/G.wav"),
    enSound: require("assets/audio/alphabet/en/G.wav"),
    image: require("assets/images/alphabet/G.jpg"),
  },
  {
    en: "H",
    viSound: require("assets/audio/alphabet/vi/H.wav"),
    enSound: require("assets/audio/alphabet/en/H.wav"),
    image: require("assets/images/alphabet/H.jpg"),
  },
  {
    en: "I",
    viSound: require("assets/audio/alphabet/vi/I.wav"),
    enSound: require("assets/audio/alphabet/en/I.wav"),
    image: require("assets/images/alphabet/I.jpg"),
  },
  {
    en: "J",
    viSound: require("assets/audio/alphabet/vi/J.wav"),
    enSound: require("assets/audio/alphabet/en/J.wav"),
    image: require("assets/images/alphabet/J.jpg"),
  },
  {
    en: "K",
    viSound: require("assets/audio/alphabet/vi/K.wav"),
    enSound: require("assets/audio/alphabet/en/K.wav"),
    image: require("assets/images/alphabet/K.jpg"),
  },
  {
    en: "L",
    viSound: require("assets/audio/alphabet/vi/L.wav"),
    enSound: require("assets/audio/alphabet/en/L.wav"),
    image: require("assets/images/alphabet/L.jpg"),
  },
  {
    en: "M",
    viSound: require("assets/audio/alphabet/vi/M.wav"),
    enSound: require("assets/audio/alphabet/en/M.wav"),
    image: require("assets/images/alphabet/M.jpg"),
  },
  {
    en: "N",
    viSound: require("assets/audio/alphabet/vi/N.wav"),
    enSound: require("assets/audio/alphabet/en/N.wav"),
    image: require("assets/images/alphabet/N.jpg"),
  },
  {
    en: "O",
    viSound: require("assets/audio/alphabet/vi/O.wav"),
    enSound: require("assets/audio/alphabet/en/O.wav"),
    image: require("assets/images/alphabet/O.jpg"),
  },
  {
    en: "P",
    viSound: require("assets/audio/alphabet/vi/P.wav"),
    enSound: require("assets/audio/alphabet/en/P.wav"),
    image: require("assets/images/alphabet/P.jpg"),
  },
  {
    en: "Q",
    viSound: require("assets/audio/alphabet/vi/Q.wav"),
    enSound: require("assets/audio/alphabet/en/Q.wav"),
    image: require("assets/images/alphabet/Q.jpg"),
  },
  {
    en: "R",
    viSound: require("assets/audio/alphabet/vi/R.wav"),
    enSound: require("assets/audio/alphabet/en/R.wav"),
    image: require("assets/images/alphabet/R.jpg"),
  },
  {
    en: "S",
    viSound: require("assets/audio/alphabet/vi/S.wav"),
    enSound: require("assets/audio/alphabet/en/S.wav"),
    image: require("assets/images/alphabet/S.jpg"),
  },
  {
    en: "T",
    viSound: require("assets/audio/alphabet/vi/T.wav"),
    enSound: require("assets/audio/alphabet/en/T.wav"),
    image: require("assets/images/alphabet/T.jpg"),
  },
  {
    en: "U",
    viSound: require("assets/audio/alphabet/vi/U.wav"),
    enSound: require("assets/audio/alphabet/en/U.wav"),
    image: require("assets/images/alphabet/U.jpg"),
  },
  {
    en: "V",
    viSound: require("assets/audio/alphabet/vi/V.wav"),
    enSound: require("assets/audio/alphabet/en/V.wav"),
    image: require("assets/images/alphabet/V.jpg"),
  },
  {
    en: "W",
    viSound: require("assets/audio/alphabet/vi/W.wav"),
    enSound: require("assets/audio/alphabet/en/W.wav"),
    image: require("assets/images/alphabet/W.jpg"),
  },
  {
    en: "X",
    viSound: require("assets/audio/alphabet/vi/X.wav"),
    enSound: require("assets/audio/alphabet/en/X.wav"),
    image: require("assets/images/alphabet/X.jpg"),
  },
  {
    en: "Y",
    viSound: require("assets/audio/alphabet/vi/Y.wav"),
    enSound: require("assets/audio/alphabet/en/Y.wav"),
    image: require("assets/images/alphabet/Y.jpg"),
  },
  {
    en: "Z",
    viSound: require("assets/audio/alphabet/vi/Z.wav"),
    enSound: require("assets/audio/alphabet/en/Z.wav"),
    image: require("assets/images/alphabet/Z.jpg"),
  },
  {
    en: "amusement-park",
    viSound: require("assets/audio/amusement-park/vi/amusement-park.wav"),
    enSound: require("assets/audio/amusement-park/en/amusement-park.wav"),
    image: require("assets/images/amusement-park/amusement-park.jpg"),
  },
  {
    en: "boat-swing",
    viSound: require("assets/audio/amusement-park/vi/boat-swing.wav"),
    enSound: require("assets/audio/amusement-park/en/boat-swing.wav"),
    image: require("assets/images/amusement-park/boat-swing.jpg"),
  },
  {
    en: "bouncy-castle",
    viSound: require("assets/audio/amusement-park/vi/bouncy-castle.wav"),
    enSound: require("assets/audio/amusement-park/en/bouncy-castle.wav"),
    image: require("assets/images/amusement-park/bouncy-castle.jpg"),
  },
  {
    en: "bumper-cars",
    viSound: require("assets/audio/amusement-park/vi/bumper-cars.wav"),
    enSound: require("assets/audio/amusement-park/en/bumper-cars.wav"),
    image: require("assets/images/amusement-park/bumper-cars.jpg"),
  },
  {
    en: "chair-swing",
    viSound: require("assets/audio/amusement-park/vi/chair-swing.wav"),
    enSound: require("assets/audio/amusement-park/en/chair-swing.wav"),
    image: require("assets/images/amusement-park/chair-swing.jpg"),
  },
  {
    en: "cup-and-saucer",
    viSound: require("assets/audio/amusement-park/vi/cup-and-saucer.wav"),
    enSound: require("assets/audio/amusement-park/en/cup-and-saucer.wav"),
    image: require("assets/images/amusement-park/cup-and-saucer.jpg"),
  },
  {
    en: "ferris-wheel",
    viSound: require("assets/audio/amusement-park/vi/ferris-wheel.wav"),
    enSound: require("assets/audio/amusement-park/en/ferris-wheel.wav"),
    image: require("assets/images/amusement-park/ferris-wheel.jpg"),
  },
  {
    en: "go-karts",
    viSound: require("assets/audio/amusement-park/vi/go-karts.wav"),
    enSound: require("assets/audio/amusement-park/en/go-karts.wav"),
    image: require("assets/images/amusement-park/go-karts.jpg"),
  },
  {
    en: "haunted-house",
    viSound: require("assets/audio/amusement-park/vi/haunted-house.wav"),
    enSound: require("assets/audio/amusement-park/en/haunted-house.wav"),
    image: require("assets/images/amusement-park/haunted-house.jpg"),
  },
  {
    en: "merry-go-round",
    viSound: require("assets/audio/amusement-park/vi/merry-go-round.wav"),
    enSound: require("assets/audio/amusement-park/en/merry-go-round.wav"),
    image: require("assets/images/amusement-park/merry-go-round.jpg"),
  },
  {
    en: "roller-coaster",
    viSound: require("assets/audio/amusement-park/vi/roller-coaster.wav"),
    enSound: require("assets/audio/amusement-park/en/roller-coaster.wav"),
    image: require("assets/images/amusement-park/roller-coaster.jpg"),
  },
  {
    en: "ticket-booth",
    viSound: require("assets/audio/amusement-park/vi/ticket-booth.wav"),
    enSound: require("assets/audio/amusement-park/en/ticket-booth.wav"),
    image: require("assets/images/amusement-park/ticket-booth.jpg"),
  },
  {
    en: "Lemur",
    viSound: require("assets/audio/animal/vi/Lemur.wav"),
    enSound: require("assets/audio/animal/en/Lemur.wav"),
    image: require("assets/images/animal/Lemur.jpg"),
  },
  {
    en: "Lizard",
    viSound: require("assets/audio/animal/vi/Lizard.wav"),
    enSound: require("assets/audio/animal/en/Lizard.wav"),
    image: require("assets/images/animal/Lizard.jpg"),
  },
  {
    en: "Lobster",
    viSound: require("assets/audio/animal/vi/Lobster.wav"),
    enSound: require("assets/audio/animal/en/Lobster.wav"),
    image: require("assets/images/animal/Lobster.jpg"),
  },
  {
    en: "alligator",
    viSound: require("assets/audio/animal/vi/alligator.wav"),
    enSound: require("assets/audio/animal/en/alligator.wav"),
    image: require("assets/images/animal/alligator.jpg"),
  },
  {
    en: "anteater",
    viSound: require("assets/audio/animal/vi/anteater.wav"),
    enSound: require("assets/audio/animal/en/anteater.wav"),
    image: require("assets/images/animal/anteater.jpg"),
  },
  {
    en: "artic-fox",
    viSound: require("assets/audio/animal/vi/artic-fox.wav"),
    enSound: require("assets/audio/animal/en/artic-fox.wav"),
    image: require("assets/images/animal/artic-fox.jpg"),
  },
  {
    en: "badger",
    viSound: require("assets/audio/animal/vi/badger.wav"),
    enSound: require("assets/audio/animal/en/badger.wav"),
    image: require("assets/images/animal/badger.jpg"),
  },
  {
    en: "bat",
    viSound: require("assets/audio/animal/vi/bat.wav"),
    enSound: require("assets/audio/animal/en/bat.wav"),
    image: require("assets/images/animal/bat.jpg"),
  },
  {
    en: "bear",
    viSound: require("assets/audio/animal/vi/bear.wav"),
    enSound: require("assets/audio/animal/en/bear.wav"),
    image: require("assets/images/animal/bear.jpg"),
  },
  {
    en: "beaver",
    viSound: require("assets/audio/animal/vi/beaver.wav"),
    enSound: require("assets/audio/animal/en/beaver.wav"),
    image: require("assets/images/animal/beaver.jpg"),
  },
  {
    en: "bird",
    viSound: require("assets/audio/animal/vi/bird.wav"),
    enSound: require("assets/audio/animal/en/bird.wav"),
    image: require("assets/images/animal/bird.jpg"),
  },
  {
    en: "bison",
    viSound: require("assets/audio/animal/vi/bison.wav"),
    enSound: require("assets/audio/animal/en/bison.wav"),
    image: require("assets/images/animal/bison.jpg"),
  },
  {
    en: "boar",
    viSound: require("assets/audio/animal/vi/boar.wav"),
    enSound: require("assets/audio/animal/en/boar.wav"),
    image: require("assets/images/animal/boar.jpg"),
  },
  {
    en: "bugs",
    viSound: require("assets/audio/animal/vi/bugs.wav"),
    enSound: require("assets/audio/animal/en/bugs.wav"),
    image: require("assets/images/animal/bugs.jpg"),
  },
  {
    en: "camel",
    viSound: require("assets/audio/animal/vi/camel.wav"),
    enSound: require("assets/audio/animal/en/camel.wav"),
    image: require("assets/images/animal/camel.jpg"),
  },
  {
    en: "cat",
    viSound: require("assets/audio/animal/vi/cat.wav"),
    enSound: require("assets/audio/animal/en/cat.wav"),
    image: require("assets/images/animal/cat.jpg"),
  },
  {
    en: "chicken",
    viSound: require("assets/audio/animal/vi/chicken.wav"),
    enSound: require("assets/audio/animal/en/chicken.wav"),
    image: require("assets/images/animal/chicken.jpg"),
  },
  {
    en: "cow",
    viSound: require("assets/audio/animal/vi/cow.wav"),
    enSound: require("assets/audio/animal/en/cow.wav"),
    image: require("assets/images/animal/cow.jpg"),
  },
  {
    en: "coyote",
    viSound: require("assets/audio/animal/vi/coyote.wav"),
    enSound: require("assets/audio/animal/en/coyote.wav"),
    image: require("assets/images/animal/coyote.jpg"),
  },
  {
    en: "crab",
    viSound: require("assets/audio/animal/vi/crab.wav"),
    enSound: require("assets/audio/animal/en/crab.wav"),
    image: require("assets/images/animal/crab.jpg"),
  },
  {
    en: "crocodile",
    viSound: require("assets/audio/animal/vi/crocodile.wav"),
    enSound: require("assets/audio/animal/en/crocodile.wav"),
    image: require("assets/images/animal/crocodile.jpg"),
  },
  {
    en: "deer",
    viSound: require("assets/audio/animal/vi/deer.wav"),
    enSound: require("assets/audio/animal/en/deer.wav"),
    image: require("assets/images/animal/deer.jpg"),
  },
  {
    en: "dog",
    viSound: require("assets/audio/animal/vi/dog.wav"),
    enSound: require("assets/audio/animal/en/dog.wav"),
    image: require("assets/images/animal/dog.jpg"),
  },
  {
    en: "dolphin",
    viSound: require("assets/audio/animal/vi/dolphin.wav"),
    enSound: require("assets/audio/animal/en/dolphin.wav"),
    image: require("assets/images/animal/dolphin.jpg"),
  },
  {
    en: "donkey",
    viSound: require("assets/audio/animal/vi/donkey.wav"),
    enSound: require("assets/audio/animal/en/donkey.wav"),
    image: require("assets/images/animal/donkey.jpg"),
  },
  {
    en: "duck",
    viSound: require("assets/audio/animal/vi/duck.wav"),
    enSound: require("assets/audio/animal/en/duck.wav"),
    image: require("assets/images/animal/duck.jpg"),
  },
  {
    en: "eagle",
    viSound: require("assets/audio/animal/vi/eagle.wav"),
    enSound: require("assets/audio/animal/en/eagle.wav"),
    image: require("assets/images/animal/eagle.jpg"),
  },
  {
    en: "eel",
    viSound: require("assets/audio/animal/vi/eel.wav"),
    enSound: require("assets/audio/animal/en/eel.wav"),
    image: require("assets/images/animal/eel.jpg"),
  },
  {
    en: "elephant",
    viSound: require("assets/audio/animal/vi/elephant.wav"),
    enSound: require("assets/audio/animal/en/elephant.wav"),
    image: require("assets/images/animal/elephant.jpg"),
  },
  {
    en: "fish",
    viSound: require("assets/audio/animal/vi/fish.wav"),
    enSound: require("assets/audio/animal/en/fish.wav"),
    image: require("assets/images/animal/fish.jpg"),
  },
  {
    en: "flamingo",
    viSound: require("assets/audio/animal/vi/flamingo.wav"),
    enSound: require("assets/audio/animal/en/flamingo.wav"),
    image: require("assets/images/animal/flamingo.jpg"),
  },
  {
    en: "fox",
    viSound: require("assets/audio/animal/vi/fox.wav"),
    enSound: require("assets/audio/animal/en/fox.wav"),
    image: require("assets/images/animal/fox.jpg"),
  },
  {
    en: "frog",
    viSound: require("assets/audio/animal/vi/frog.wav"),
    enSound: require("assets/audio/animal/en/frog.wav"),
    image: require("assets/images/animal/frog.jpg"),
  },
  {
    en: "giraffe",
    viSound: require("assets/audio/animal/vi/giraffe.wav"),
    enSound: require("assets/audio/animal/en/giraffe.wav"),
    image: require("assets/images/animal/giraffe.jpg"),
  },
  {
    en: "goat",
    viSound: require("assets/audio/animal/vi/goat.wav"),
    enSound: require("assets/audio/animal/en/goat.wav"),
    image: require("assets/images/animal/goat.jpg"),
  },
  {
    en: "gorilla",
    viSound: require("assets/audio/animal/vi/gorilla.wav"),
    enSound: require("assets/audio/animal/en/gorilla.wav"),
    image: require("assets/images/animal/gorilla.jpg"),
  },
  {
    en: "guinea-pig",
    viSound: require("assets/audio/animal/vi/guinea-pig.wav"),
    enSound: require("assets/audio/animal/en/guinea-pig.wav"),
    image: require("assets/images/animal/guinea-pig.jpg"),
  },
  {
    en: "hawk",
    viSound: require("assets/audio/animal/vi/hawk.wav"),
    enSound: require("assets/audio/animal/en/hawk.wav"),
    image: require("assets/images/animal/hawk.jpg"),
  },
  {
    en: "hedgehog",
    viSound: require("assets/audio/animal/vi/hedgehog.wav"),
    enSound: require("assets/audio/animal/en/hedgehog.wav"),
    image: require("assets/images/animal/hedgehog.jpg"),
  },
  {
    en: "hen",
    viSound: require("assets/audio/animal/vi/hen.wav"),
    enSound: require("assets/audio/animal/en/hen.wav"),
    image: require("assets/images/animal/hen.jpg"),
  },
  {
    en: "hippo",
    viSound: require("assets/audio/animal/vi/hippo.wav"),
    enSound: require("assets/audio/animal/en/hippo.wav"),
    image: require("assets/images/animal/hippo.jpg"),
  },
  {
    en: "horse",
    viSound: require("assets/audio/animal/vi/horse.wav"),
    enSound: require("assets/audio/animal/en/horse.wav"),
    image: require("assets/images/animal/horse.jpg"),
  },
  {
    en: "hyena",
    viSound: require("assets/audio/animal/vi/hyena.wav"),
    enSound: require("assets/audio/animal/en/hyena.wav"),
    image: require("assets/images/animal/hyena.jpg"),
  },
  {
    en: "iguana",
    viSound: require("assets/audio/animal/vi/iguana.wav"),
    enSound: require("assets/audio/animal/en/iguana.wav"),
    image: require("assets/images/animal/iguana.jpg"),
  },
  {
    en: "jellyfish",
    viSound: require("assets/audio/animal/vi/jellyfish.wav"),
    enSound: require("assets/audio/animal/en/jellyfish.wav"),
    image: require("assets/images/animal/jellyfish.jpg"),
  },
  {
    en: "kangaroo",
    viSound: require("assets/audio/animal/vi/kangaroo.wav"),
    enSound: require("assets/audio/animal/en/kangaroo.wav"),
    image: require("assets/images/animal/kangaroo.jpg"),
  },
  {
    en: "killer-whale",
    viSound: require("assets/audio/animal/vi/killer-whale.wav"),
    enSound: require("assets/audio/animal/en/killer-whale.wav"),
    image: require("assets/images/animal/killer-whale.jpg"),
  },
  {
    en: "koala",
    viSound: require("assets/audio/animal/vi/koala.wav"),
    enSound: require("assets/audio/animal/en/koala.wav"),
    image: require("assets/images/animal/koala.jpg"),
  },
  {
    en: "leopard",
    viSound: require("assets/audio/animal/vi/leopard.wav"),
    enSound: require("assets/audio/animal/en/leopard.wav"),
    image: require("assets/images/animal/leopard.jpg"),
  },
  {
    en: "lion",
    viSound: require("assets/audio/animal/vi/lion.wav"),
    enSound: require("assets/audio/animal/en/lion.wav"),
    image: require("assets/images/animal/lion.jpg"),
  },
  {
    en: "llama",
    viSound: require("assets/audio/animal/vi/llama.wav"),
    enSound: require("assets/audio/animal/en/llama.wav"),
    image: require("assets/images/animal/llama.jpg"),
  },
  {
    en: "mole",
    viSound: require("assets/audio/animal/vi/mole.wav"),
    enSound: require("assets/audio/animal/en/mole.wav"),
    image: require("assets/images/animal/mole.jpg"),
  },
  {
    en: "monkey",
    viSound: require("assets/audio/animal/vi/monkey.wav"),
    enSound: require("assets/audio/animal/en/monkey.wav"),
    image: require("assets/images/animal/monkey.jpg"),
  },
  {
    en: "moose",
    viSound: require("assets/audio/animal/vi/moose.wav"),
    enSound: require("assets/audio/animal/en/moose.wav"),
    image: require("assets/images/animal/moose.jpg"),
  },
  {
    en: "mouse",
    viSound: require("assets/audio/animal/vi/mouse.wav"),
    enSound: require("assets/audio/animal/en/mouse.wav"),
    image: require("assets/images/animal/mouse.jpg"),
  },
  {
    en: "narwhal",
    viSound: require("assets/audio/animal/vi/narwhal.wav"),
    enSound: require("assets/audio/animal/en/narwhal.wav"),
    image: require("assets/images/animal/narwhal.jpg"),
  },
  {
    en: "newt",
    viSound: require("assets/audio/animal/vi/newt.wav"),
    enSound: require("assets/audio/animal/en/newt.wav"),
    image: require("assets/images/animal/newt.jpg"),
  },
  {
    en: "octopus",
    viSound: require("assets/audio/animal/vi/octopus.wav"),
    enSound: require("assets/audio/animal/en/octopus.wav"),
    image: require("assets/images/animal/octopus.jpg"),
  },
  {
    en: "ostritch",
    viSound: require("assets/audio/animal/vi/ostritch.wav"),
    enSound: require("assets/audio/animal/en/ostritch.wav"),
    image: require("assets/images/animal/ostritch.jpg"),
  },
  {
    en: "otter",
    viSound: require("assets/audio/animal/vi/otter.wav"),
    enSound: require("assets/audio/animal/en/otter.wav"),
    image: require("assets/images/animal/otter.jpg"),
  },
  {
    en: "owl",
    viSound: require("assets/audio/animal/vi/owl.wav"),
    enSound: require("assets/audio/animal/en/owl.wav"),
    image: require("assets/images/animal/owl.jpg"),
  },
  {
    en: "panda",
    viSound: require("assets/audio/animal/vi/panda.wav"),
    enSound: require("assets/audio/animal/en/panda.wav"),
    image: require("assets/images/animal/panda.jpg"),
  },
  {
    en: "parrot",
    viSound: require("assets/audio/animal/vi/parrot.wav"),
    enSound: require("assets/audio/animal/en/parrot.wav"),
    image: require("assets/images/animal/parrot.jpg"),
  },
  {
    en: "peacock",
    viSound: require("assets/audio/animal/vi/peacock.wav"),
    enSound: require("assets/audio/animal/en/peacock.wav"),
    image: require("assets/images/animal/peacock.jpg"),
  },
  {
    en: "penguin",
    viSound: require("assets/audio/animal/vi/penguin.wav"),
    enSound: require("assets/audio/animal/en/penguin.wav"),
    image: require("assets/images/animal/penguin.jpg"),
  },
  {
    en: "pig",
    viSound: require("assets/audio/animal/vi/pig.wav"),
    enSound: require("assets/audio/animal/en/pig.wav"),
    image: require("assets/images/animal/pig.jpg"),
  },
  {
    en: "pigeon",
    viSound: require("assets/audio/animal/vi/pigeon.wav"),
    enSound: require("assets/audio/animal/en/pigeon.wav"),
    image: require("assets/images/animal/pigeon.jpg"),
  },
  {
    en: "plankton",
    viSound: require("assets/audio/animal/vi/plankton.wav"),
    enSound: require("assets/audio/animal/en/plankton.wav"),
    image: require("assets/images/animal/plankton.jpg"),
  },
  {
    en: "platypus",
    viSound: require("assets/audio/animal/vi/platypus.wav"),
    enSound: require("assets/audio/animal/en/platypus.wav"),
    image: require("assets/images/animal/platypus.jpg"),
  },
  {
    en: "polar-bear",
    viSound: require("assets/audio/animal/vi/polar-bear.wav"),
    enSound: require("assets/audio/animal/en/polar-bear.wav"),
    image: require("assets/images/animal/polar-bear.jpg"),
  },
  {
    en: "puffin",
    viSound: require("assets/audio/animal/vi/puffin.wav"),
    enSound: require("assets/audio/animal/en/puffin.wav"),
    image: require("assets/images/animal/puffin.jpg"),
  },
  {
    en: "quail",
    viSound: require("assets/audio/animal/vi/quail.wav"),
    enSound: require("assets/audio/animal/en/quail.wav"),
    image: require("assets/images/animal/quail.jpg"),
  },
  {
    en: "queen-bee",
    viSound: require("assets/audio/animal/vi/queen-bee.wav"),
    enSound: require("assets/audio/animal/en/queen-bee.wav"),
    image: require("assets/images/animal/queen-bee.jpg"),
  },
  {
    en: "rabbit",
    viSound: require("assets/audio/animal/vi/rabbit.wav"),
    enSound: require("assets/audio/animal/en/rabbit.wav"),
    image: require("assets/images/animal/rabbit.jpg"),
  },
  {
    en: "racoon",
    viSound: require("assets/audio/animal/vi/racoon.wav"),
    enSound: require("assets/audio/animal/en/racoon.wav"),
    image: require("assets/images/animal/racoon.jpg"),
  },
  {
    en: "rat",
    viSound: require("assets/audio/animal/vi/rat.wav"),
    enSound: require("assets/audio/animal/en/rat.wav"),
    image: require("assets/images/animal/rat.jpg"),
  },
  {
    en: "rhino",
    viSound: require("assets/audio/animal/vi/rhino.wav"),
    enSound: require("assets/audio/animal/en/rhino.wav"),
    image: require("assets/images/animal/rhino.jpg"),
  },
  {
    en: "rooster",
    viSound: require("assets/audio/animal/vi/rooster.wav"),
    enSound: require("assets/audio/animal/en/rooster.wav"),
    image: require("assets/images/animal/rooster.jpg"),
  },
  {
    en: "scorpion",
    viSound: require("assets/audio/animal/vi/scorpion.wav"),
    enSound: require("assets/audio/animal/en/scorpion.wav"),
    image: require("assets/images/animal/scorpion.jpg"),
  },
  {
    en: "seagul",
    viSound: require("assets/audio/animal/vi/seagul.wav"),
    enSound: require("assets/audio/animal/en/seagul.wav"),
    image: require("assets/images/animal/seagul.jpg"),
  },
  {
    en: "seahorse",
    viSound: require("assets/audio/animal/vi/seahorse.wav"),
    enSound: require("assets/audio/animal/en/seahorse.wav"),
    image: require("assets/images/animal/seahorse.jpg"),
  },
  {
    en: "seal",
    viSound: require("assets/audio/animal/vi/seal.wav"),
    enSound: require("assets/audio/animal/en/seal.wav"),
    image: require("assets/images/animal/seal.jpg"),
  },
  {
    en: "shark",
    viSound: require("assets/audio/animal/vi/shark.wav"),
    enSound: require("assets/audio/animal/en/shark.wav"),
    image: require("assets/images/animal/shark.jpg"),
  },
  {
    en: "sheep",
    viSound: require("assets/audio/animal/vi/sheep.wav"),
    enSound: require("assets/audio/animal/en/sheep.wav"),
    image: require("assets/images/animal/sheep.jpg"),
  },
  {
    en: "shrimp",
    viSound: require("assets/audio/animal/vi/shrimp.wav"),
    enSound: require("assets/audio/animal/en/shrimp.wav"),
    image: require("assets/images/animal/shrimp.jpg"),
  },
  {
    en: "skunk",
    viSound: require("assets/audio/animal/vi/skunk.wav"),
    enSound: require("assets/audio/animal/en/skunk.wav"),
    image: require("assets/images/animal/skunk.jpg"),
  },
  {
    en: "sloth",
    viSound: require("assets/audio/animal/vi/sloth.wav"),
    enSound: require("assets/audio/animal/en/sloth.wav"),
    image: require("assets/images/animal/sloth.jpg"),
  },
  {
    en: "snake",
    viSound: require("assets/audio/animal/vi/snake.wav"),
    enSound: require("assets/audio/animal/en/snake.wav"),
    image: require("assets/images/animal/snake.jpg"),
  },
  {
    en: "squid",
    viSound: require("assets/audio/animal/vi/squid.wav"),
    enSound: require("assets/audio/animal/en/squid.wav"),
    image: require("assets/images/animal/squid.jpg"),
  },
  {
    en: "squirrel",
    viSound: require("assets/audio/animal/vi/squirrel.wav"),
    enSound: require("assets/audio/animal/en/squirrel.wav"),
    image: require("assets/images/animal/squirrel.jpg"),
  },
  {
    en: "starfish",
    viSound: require("assets/audio/animal/vi/starfish.wav"),
    enSound: require("assets/audio/animal/en/starfish.wav"),
    image: require("assets/images/animal/starfish.jpg"),
  },
  {
    en: "stingray",
    viSound: require("assets/audio/animal/vi/stingray.wav"),
    enSound: require("assets/audio/animal/en/stingray.wav"),
    image: require("assets/images/animal/stingray.jpg"),
  },
  {
    en: "swordfish",
    viSound: require("assets/audio/animal/vi/swordfish.wav"),
    enSound: require("assets/audio/animal/en/swordfish.wav"),
    image: require("assets/images/animal/swordfish.jpg"),
  },
  {
    en: "tarantula",
    viSound: require("assets/audio/animal/vi/tarantula.wav"),
    enSound: require("assets/audio/animal/en/tarantula.wav"),
    image: require("assets/images/animal/tarantula.jpg"),
  },
  {
    en: "tiger",
    viSound: require("assets/audio/animal/vi/tiger.wav"),
    enSound: require("assets/audio/animal/en/tiger.wav"),
    image: require("assets/images/animal/tiger.jpg"),
  },
  {
    en: "toucan",
    viSound: require("assets/audio/animal/vi/toucan.wav"),
    enSound: require("assets/audio/animal/en/toucan.wav"),
    image: require("assets/images/animal/toucan.jpg"),
  },
  {
    en: "turtle",
    viSound: require("assets/audio/animal/vi/turtle.wav"),
    enSound: require("assets/audio/animal/en/turtle.wav"),
    image: require("assets/images/animal/turtle.jpg"),
  },
  {
    en: "urchin",
    viSound: require("assets/audio/animal/vi/urchin.wav"),
    enSound: require("assets/audio/animal/en/urchin.wav"),
    image: require("assets/images/animal/urchin.jpg"),
  },
  {
    en: "vulture",
    viSound: require("assets/audio/animal/vi/vulture.wav"),
    enSound: require("assets/audio/animal/en/vulture.wav"),
    image: require("assets/images/animal/vulture.jpg"),
  },
  {
    en: "walrus",
    viSound: require("assets/audio/animal/vi/walrus.wav"),
    enSound: require("assets/audio/animal/en/walrus.wav"),
    image: require("assets/images/animal/walrus.jpg"),
  },
  {
    en: "whale",
    viSound: require("assets/audio/animal/vi/whale.wav"),
    enSound: require("assets/audio/animal/en/whale.wav"),
    image: require("assets/images/animal/whale.jpg"),
  },
  {
    en: "wolf",
    viSound: require("assets/audio/animal/vi/wolf.wav"),
    enSound: require("assets/audio/animal/en/wolf.wav"),
    image: require("assets/images/animal/wolf.jpg"),
  },
  {
    en: "x-ray-fish",
    viSound: require("assets/audio/animal/vi/x-ray-fish.wav"),
    enSound: require("assets/audio/animal/en/x-ray-fish.wav"),
    image: require("assets/images/animal/x-ray-fish.jpg"),
  },
  {
    en: "yak",
    viSound: require("assets/audio/animal/vi/yak.wav"),
    enSound: require("assets/audio/animal/en/yak.wav"),
    image: require("assets/images/animal/yak.jpg"),
  },
  {
    en: "zebra",
    viSound: require("assets/audio/animal/vi/zebra.wav"),
    enSound: require("assets/audio/animal/en/zebra.wav"),
    image: require("assets/images/animal/zebra.jpg"),
  },
  {
    en: "Q-tip",
    viSound: require("assets/audio/bathroom/vi/Q-tip.wav"),
    enSound: require("assets/audio/bathroom/en/Q-tip.wav"),
    image: require("assets/images/bathroom/Q-tip.jpg"),
  },
  {
    en: "bath-mat",
    viSound: require("assets/audio/bathroom/vi/bath-mat.wav"),
    enSound: require("assets/audio/bathroom/en/bath-mat.wav"),
    image: require("assets/images/bathroom/bath-mat.jpg"),
  },
  {
    en: "bathroom",
    viSound: require("assets/audio/bathroom/vi/bathroom.wav"),
    enSound: require("assets/audio/bathroom/en/bathroom.wav"),
    image: require("assets/images/bathroom/bathroom.jpg"),
  },
  {
    en: "bathtub",
    viSound: require("assets/audio/bathroom/vi/bathtub.wav"),
    enSound: require("assets/audio/bathroom/en/bathtub.wav"),
    image: require("assets/images/bathroom/bathtub.jpg"),
  },
  {
    en: "brush",
    viSound: require("assets/audio/bathroom/vi/brush.wav"),
    enSound: require("assets/audio/bathroom/en/brush.wav"),
    image: require("assets/images/bathroom/brush.jpg"),
  },
  {
    en: "comb",
    viSound: require("assets/audio/bathroom/vi/comb.wav"),
    enSound: require("assets/audio/bathroom/en/comb.wav"),
    image: require("assets/images/bathroom/comb.jpg"),
  },
  {
    en: "dental-floss",
    viSound: require("assets/audio/bathroom/vi/dental-floss.wav"),
    enSound: require("assets/audio/bathroom/en/dental-floss.wav"),
    image: require("assets/images/bathroom/dental-floss.jpg"),
  },
  {
    en: "hair-dryer",
    viSound: require("assets/audio/bathroom/vi/hair-dryer.wav"),
    enSound: require("assets/audio/bathroom/en/hair-dryer.wav"),
    image: require("assets/images/bathroom/hair-dryer.jpg"),
  },
  {
    en: "hand-towel",
    viSound: require("assets/audio/bathroom/vi/hand-towel.wav"),
    enSound: require("assets/audio/bathroom/en/hand-towel.wav"),
    image: require("assets/images/bathroom/hand-towel.jpg"),
  },
  {
    en: "lotion",
    viSound: require("assets/audio/bathroom/vi/lotion.wav"),
    enSound: require("assets/audio/bathroom/en/lotion.wav"),
    image: require("assets/images/bathroom/lotion.jpg"),
  },
  {
    en: "makeup",
    viSound: require("assets/audio/bathroom/vi/makeup.wav"),
    enSound: require("assets/audio/bathroom/en/makeup.wav"),
    image: require("assets/images/bathroom/makeup.jpg"),
  },
  {
    en: "mirror",
    viSound: require("assets/audio/bathroom/vi/mirror.wav"),
    enSound: require("assets/audio/bathroom/en/mirror.wav"),
    image: require("assets/images/bathroom/mirror.jpg"),
  },
  {
    en: "mouthwash",
    viSound: require("assets/audio/bathroom/vi/mouthwash.wav"),
    enSound: require("assets/audio/bathroom/en/mouthwash.wav"),
    image: require("assets/images/bathroom/mouthwash.jpg"),
  },
  {
    en: "razor",
    viSound: require("assets/audio/bathroom/vi/razor.wav"),
    enSound: require("assets/audio/bathroom/en/razor.wav"),
    image: require("assets/images/bathroom/razor.jpg"),
  },
  {
    en: "shampoo",
    viSound: require("assets/audio/bathroom/vi/shampoo.wav"),
    enSound: require("assets/audio/bathroom/en/shampoo.wav"),
    image: require("assets/images/bathroom/shampoo.jpg"),
  },
  {
    en: "shaving-cream",
    viSound: require("assets/audio/bathroom/vi/shaving-cream.wav"),
    enSound: require("assets/audio/bathroom/en/shaving-cream.wav"),
    image: require("assets/images/bathroom/shaving-cream.jpg"),
  },
  {
    en: "shower",
    viSound: require("assets/audio/bathroom/vi/shower.wav"),
    enSound: require("assets/audio/bathroom/en/shower.wav"),
    image: require("assets/images/bathroom/shower.jpg"),
  },
  {
    en: "sink",
    viSound: require("assets/audio/bathroom/vi/sink.wav"),
    enSound: require("assets/audio/bathroom/en/sink.wav"),
    image: require("assets/images/bathroom/sink.jpg"),
  },
  {
    en: "soap",
    viSound: require("assets/audio/bathroom/vi/soap.wav"),
    enSound: require("assets/audio/bathroom/en/soap.wav"),
    image: require("assets/images/bathroom/soap.jpg"),
  },
  {
    en: "sponge",
    viSound: require("assets/audio/bathroom/vi/sponge.wav"),
    enSound: require("assets/audio/bathroom/en/sponge.wav"),
    image: require("assets/images/bathroom/sponge.jpg"),
  },
  {
    en: "tap",
    viSound: require("assets/audio/bathroom/vi/tap.wav"),
    enSound: require("assets/audio/bathroom/en/tap.wav"),
    image: require("assets/images/bathroom/tap.jpg"),
  },
  {
    en: "toilet-paper",
    viSound: require("assets/audio/bathroom/vi/toilet-paper.wav"),
    enSound: require("assets/audio/bathroom/en/toilet-paper.wav"),
    image: require("assets/images/bathroom/toilet-paper.jpg"),
  },
  {
    en: "toilet",
    viSound: require("assets/audio/bathroom/vi/toilet.wav"),
    enSound: require("assets/audio/bathroom/en/toilet.wav"),
    image: require("assets/images/bathroom/toilet.jpg"),
  },
  {
    en: "toothbrush",
    viSound: require("assets/audio/bathroom/vi/toothbrush.wav"),
    enSound: require("assets/audio/bathroom/en/toothbrush.wav"),
    image: require("assets/images/bathroom/toothbrush.jpg"),
  },
  {
    en: "toothpaste",
    viSound: require("assets/audio/bathroom/vi/toothpaste.wav"),
    enSound: require("assets/audio/bathroom/en/toothpaste.wav"),
    image: require("assets/images/bathroom/toothpaste.jpg"),
  },
  {
    en: "towel",
    viSound: require("assets/audio/bathroom/vi/towel.wav"),
    enSound: require("assets/audio/bathroom/en/towel.wav"),
    image: require("assets/images/bathroom/towel.jpg"),
  },
  {
    en: "eight",
    viSound: require("assets/audio/number/vi/eight.wav"),
    enSound: require("assets/audio/number/en/eight.wav"),
    image: require("assets/images/number/eight.jpg"),
  },
  {
    en: "eighteen",
    viSound: require("assets/audio/number/vi/eighteen.wav"),
    enSound: require("assets/audio/number/en/eighteen.wav"),
    image: require("assets/images/number/eighteen.jpg"),
  },
  {
    en: "eighty",
    viSound: require("assets/audio/number/vi/eighty.wav"),
    enSound: require("assets/audio/number/en/eighty.wav"),
    image: require("assets/images/number/eighty.jpg"),
  },
  {
    en: "eleven",
    viSound: require("assets/audio/number/vi/eleven.wav"),
    enSound: require("assets/audio/number/en/eleven.wav"),
    image: require("assets/images/number/eleven.jpg"),
  },
  {
    en: "fifteen",
    viSound: require("assets/audio/number/vi/fifteen.wav"),
    enSound: require("assets/audio/number/en/fifteen.wav"),
    image: require("assets/images/number/fifteen.jpg"),
  },
  {
    en: "fifty",
    viSound: require("assets/audio/number/vi/fifty.wav"),
    enSound: require("assets/audio/number/en/fifty.wav"),
    image: require("assets/images/number/fifty.jpg"),
  },
  {
    en: "five",
    viSound: require("assets/audio/number/vi/five.wav"),
    enSound: require("assets/audio/number/en/five.wav"),
    image: require("assets/images/number/five.jpg"),
  },
  {
    en: "forty",
    viSound: require("assets/audio/number/vi/forty.wav"),
    enSound: require("assets/audio/number/en/forty.wav"),
    image: require("assets/images/number/forty.jpg"),
  },
  {
    en: "four",
    viSound: require("assets/audio/number/vi/four.wav"),
    enSound: require("assets/audio/number/en/four.wav"),
    image: require("assets/images/number/four.jpg"),
  },
  {
    en: "fourteen",
    viSound: require("assets/audio/number/vi/fourteen.wav"),
    enSound: require("assets/audio/number/en/fourteen.wav"),
    image: require("assets/images/number/fourteen.jpg"),
  },
  {
    en: "nine",
    viSound: require("assets/audio/number/vi/nine.wav"),
    enSound: require("assets/audio/number/en/nine.wav"),
    image: require("assets/images/number/nine.jpg"),
  },
  {
    en: "nineteen",
    viSound: require("assets/audio/number/vi/nineteen.wav"),
    enSound: require("assets/audio/number/en/nineteen.wav"),
    image: require("assets/images/number/nineteen.jpg"),
  },
  {
    en: "ninety",
    viSound: require("assets/audio/number/vi/ninety.wav"),
    enSound: require("assets/audio/number/en/ninety.wav"),
    image: require("assets/images/number/ninety.jpg"),
  },
  {
    en: "one-hundred",
    viSound: require("assets/audio/number/vi/one-hundred.wav"),
    enSound: require("assets/audio/number/en/one-hundred.wav"),
    image: require("assets/images/number/one-hundred.jpg"),
  },
  {
    en: "one",
    viSound: require("assets/audio/number/vi/one.wav"),
    enSound: require("assets/audio/number/en/one.wav"),
    image: require("assets/images/number/one.jpg"),
  },
  {
    en: "seven",
    viSound: require("assets/audio/number/vi/seven.wav"),
    enSound: require("assets/audio/number/en/seven.wav"),
    image: require("assets/images/number/seven.jpg"),
  },
  {
    en: "seventeen",
    viSound: require("assets/audio/number/vi/seventeen.wav"),
    enSound: require("assets/audio/number/en/seventeen.wav"),
    image: require("assets/images/number/seventeen.jpg"),
  },
  {
    en: "seventy",
    viSound: require("assets/audio/number/vi/seventy.wav"),
    enSound: require("assets/audio/number/en/seventy.wav"),
    image: require("assets/images/number/seventy.jpg"),
  },
  {
    en: "six",
    viSound: require("assets/audio/number/vi/six.wav"),
    enSound: require("assets/audio/number/en/six.wav"),
    image: require("assets/images/number/six.jpg"),
  },
  {
    en: "sixteen",
    viSound: require("assets/audio/number/vi/sixteen.wav"),
    enSound: require("assets/audio/number/en/sixteen.wav"),
    image: require("assets/images/number/sixteen.jpg"),
  },
  {
    en: "sixty",
    viSound: require("assets/audio/number/vi/sixty.wav"),
    enSound: require("assets/audio/number/en/sixty.wav"),
    image: require("assets/images/number/sixty.jpg"),
  },
  {
    en: "ten",
    viSound: require("assets/audio/number/vi/ten.wav"),
    enSound: require("assets/audio/number/en/ten.wav"),
    image: require("assets/images/number/ten.jpg"),
  },
  {
    en: "thirteen",
    viSound: require("assets/audio/number/vi/thirteen.wav"),
    enSound: require("assets/audio/number/en/thirteen.wav"),
    image: require("assets/images/number/thirteen.jpg"),
  },
  {
    en: "thirty",
    viSound: require("assets/audio/number/vi/thirty.wav"),
    enSound: require("assets/audio/number/en/thirty.wav"),
    image: require("assets/images/number/thirty.jpg"),
  },
  {
    en: "three",
    viSound: require("assets/audio/number/vi/three.wav"),
    enSound: require("assets/audio/number/en/three.wav"),
    image: require("assets/images/number/three.jpg"),
  },
  {
    en: "twelve",
    viSound: require("assets/audio/number/vi/twelve.wav"),
    enSound: require("assets/audio/number/en/twelve.wav"),
    image: require("assets/images/number/twelve.jpg"),
  },
  {
    en: "twenty",
    viSound: require("assets/audio/number/vi/twenty.wav"),
    enSound: require("assets/audio/number/en/twenty.wav"),
    image: require("assets/images/number/twenty.jpg"),
  },
  {
    en: "two",
    viSound: require("assets/audio/number/vi/two.wav"),
    enSound: require("assets/audio/number/en/two.wav"),
    image: require("assets/images/number/two.jpg"),
  },
]
